// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi2.Models
{
    public partial class APP_SP_DrugsDeliveryConsumerViewSaveResult2
    {
        public string DESCRIPCION { get; set; }
        public string MENSAJE { get; set; }
    }
}
