// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
  
    public partial class APP_SP_DrugsDeliveryConsumerViewHeaderResult
    {
        public string Consumer { get; set; }
        public string License { get; set; }
        public string LicenseCategory { get; set; }
        public string LicenseExpiration { get; set; }
        public string Vehicle { get; set; }
        public string Soat { get; set; }
        public string SoatExpiration { get; set; }
        public string Crtm { get; set; }
        public string CrtmExpiration { get; set; }
    }
}
