// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class APP_SP_DrugsDeliveryConsumerViewSaveResult
    {
        public string CODIGO { get; set; }
    }
}
