// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class busca_equivalencias_formulaResult
    {
        public string medent { get; set; }
        public decimal vlrequ { get; set; }
        public string medsal { get; set; }
        public string medcod { get; set; }
    }
}
