// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class busca_prefacturaResult
    {
        public string nPrefactura { get; set; }
        public string fecha { get; set; }
        public string clinom { get; set; }
        public decimal vlrfac { get; set; }
        public int Mark { get; set; }
        public string codcli { get; set; }
        public string nrofac { get; set; }
    }
}
