// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Consumible
    {
        internal static readonly object _context;

        public int ConsumptionID { get; set; }
        public string ArticleCode { get; set; }
        public int Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public string CreationDate { get; set; }
    }
}
