// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class cuentas_pagarResult
    {
        public string nrofac { get; set; }
        public decimal vlrfac { get; set; }
        public DateTime? fecfac { get; set; }
        public decimal saldo { get; set; }
        public decimal abonof { get; set; }
        public int estado { get; set; }
        public string pronom { get; set; }
        public string pronit { get; set; }
        public string pronit1 { get; set; }
        public string protipo { get; set; }
        public string nomtipo { get; set; }
        public decimal tmpAbonos { get; set; }
        public decimal totiva { get; set; }
        public decimal vlrrtf { get; set; }
        public decimal vlrica { get; set; }
        public decimal vlrrti { get; set; }
        public decimal vlrcree { get; set; }
        public decimal VLRINI { get; set; }
        public string codrtf { get; set; }
        public string codica { get; set; }
        public string codrti { get; set; }
        public string detalle { get; set; }
        public decimal Anticipos { get; set; }
        public decimal tmpAnticipos { get; set; }
        public decimal debe { get; set; }
        public int Haber { get; set; }
        public string nrocxp { get; set; }
        public string CodImp { get; set; }
        public string CDP { get; set; }
        public string tipDoc { get; set; }
        public decimal valorAbono { get; set; }
        public decimal valorAnticipo { get; set; }
        public decimal tasa { get; set; }
    }
}
