// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class detalle_herramientaResult
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string referencia { get; set; }
        public string unidad { get; set; }
        public int prestados { get; set; }
        public string serial { get; set; }
        public string fecha_devolucion { get; set; }
        public int hdevueltos { get; set; }
        public string idmovimiento { get; set; }
        public decimal id { get; set; }
        public int disponibles { get; set; }
        public bool? insertado { get; set; }
        public bool? seriales { get; set; }
        public string dprcod { get; set; }
    }
}
