// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class detalle_herramienta2Result
    {
        public string nombre { get; set; }
        public string unidad { get; set; }
        public string codigo { get; set; }
        public string referencia { get; set; }
        public string serial { get; set; }
        public int cantidad { get; set; }
        public string observacion { get; set; }
        public string idmovimiento { get; set; }
        public decimal id { get; set; }
    }
}
