// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class edita_orden_contatacionResult
    {
        public decimal cantidad { get; set; }
        public string descrip { get; set; }
        public decimal? costo { get; set; }
        public decimal iva { get; set; }
        public decimal descuento { get; set; }
        public string cuenta { get; set; }
        public decimal consumo { get; set; }
        public int? cod { get; set; }
        public string codigocuenta { get; set; }
        public decimal reqVlr { get; set; }
        public string reqord { get; set; }
        public string reqpro { get; set; }
        public decimal? reqvlr { get; set; }
        public decimal? reqdto { get; set; }
        public decimal? reqiva { get; set; }
        public string reqfpg { get; set; }
        public string moneda { get; set; }
        public string reqcom { get; set; }
        public string reqten { get; set; }
        public string reqcco { get; set; }
        public string reqori { get; set; }
        public string reqdep { get; set; }
        public DateTime? reqfec { get; set; }
        public string otnumero { get; set; }
        public string reqobser { get; set; }
        public DateTime? fecha_orden_contra { get; set; }
        public string observacion_contratacion { get; set; }
    }
}
