// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_SDP_GET_SUCURSALES_BY_CLIENTEResult
    {
        public string DIRECCION { get; set; }
        public string UBICACION { get; set; }
        public decimal ID_SUCURSAL { get; set; }
    }
}
