// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_SALBAN_RPT_GENERALResult
    {
        public string BANCOD { get; set; }
        public string BANNOM { get; set; }
        public decimal BANSAL { get; set; }
        public string BANCH { get; set; }
        public int BANGR { get; set; }
        public DateTime BANFEC { get; set; }
        public decimal BANINI { get; set; }
        public string BANREP1 { get; set; }
        public string BANREP2 { get; set; }
        public string BANPLA { get; set; }
        public string BANNRO { get; set; }
        public string BANTIP { get; set; }
        public string TIPOCONCEPTO { get; set; }
    }
}
