// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Glapp_SP_GetUserInventoryCountsResult
    {
        public long InventoryCountID { get; set; }
        public string Consecutive { get; set; }
        public string CountingUser { get; set; }
        public string UserDisplayName { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public DateTime CreationDate { get; set; }
        public bool? IsSharing { get; set; }
    }
}
