// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_GET_ACCXP_X_TIPOResult
    {
        public string PROCOD { get; set; }
        public string PROVEEDOR { get; set; }
        public decimal? VALOR { get; set; }
        public int? N_FACTURAS { get; set; }
        public string TIPO { get; set; }
    }
}
