// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_GET_ACCXP_MAINResult
    {
        public string TIPO { get; set; }
        public decimal? VALOR { get; set; }
        public string TAG_GRUPO { get; set; }
    }
}
