// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_SDP_GET_CLIENTES_BY_NITResult
    {
        public string CLICOD { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string ESCALA { get; set; }
        public string EXISTE { get; set; }
    }
}
