// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_GET_ACCXC_FACTURAS_DETResult
    {
        public string PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string UOM { get; set; }
        public decimal? COSTO_UNITARIO { get; set; }
        public decimal IMPUESTOS { get; set; }
        public decimal TOTAL { get; set; }
    }
}
