// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_GET_ACCXP_FACTURASResult
    {
        public string PROCOD { get; set; }
        public string PROVEEDOR { get; set; }
        public string NROFAC { get; set; }
        public DateTime? FECFAC { get; set; }
        public decimal VLRFAC { get; set; }
        public string ORIGINADOR { get; set; }
    }
}
