// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_AUT_PAGOS_AUTORIZARResult
    {
        public string DESCRIPCION { get; set; }
        public string MENSAJE { get; set; }
    }
}
