// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace generalapi.Models
{
    public partial class GlappDrugsDeliveryConsumptionDet
    {
        public long ConsumptionDetailId { get; set; }
        public long ConsumptionId { get; set; }
        public string ArticleCode { get; set; }
        public decimal Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public DateTime CreationDate { get; set; }
        public decimal? Delivered { get; set; }
    }
}