// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_GET_ORDENES_AUTORIZARResult
    {
        public string REQORD { get; set; }
        public DateTime FECHA { get; set; }
        public string PRONOM { get; set; }
        public decimal REQVLR { get; set; }
        public string ORIGINADOR { get; set; }
        public int Reqtyp { get; set; }
    }
}
