// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_SDP_GET_SERVICIOSResult
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string REFERENCIA { get; set; }
        public string LINEA { get; set; }
        public string GRUPO { get; set; }
        public string ESPECIFICACION { get; set; }
        public decimal? VALOR_UNITARIO { get; set; }
        public string MEDIDA { get; set; }
        public string URL_IMAGEN { get; set; }
        public decimal IMPUESTO { get; set; }
        public decimal? VALOR_UNITARIO_BASE { get; set; }
        public int VALOR_UNIT_MINIMO { get; set; }
    }
}
