// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Glapp_SP_InventoryCountDetSaveResult
    {
        public string CODIGO { get; set; }
        public string MENSAJE { get; set; }
    }
}
