// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class GLAPP_SP_GET_ORDENES_DETALLEResult
    {
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ARREF { get; set; }
        public string MEDCOD { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal? ARCOSTO { get; set; }
        public decimal? VALOR_SIN_IVA { get; set; }
        public decimal? TOTAL { get; set; }
        public decimal? ARIVA { get; set; }
        public int PORIMP { get; set; }
        public int DESCU { get; set; }
        public int RECIBIDO { get; set; }
        public decimal FALTANTE { get; set; }
        public string MARNOM { get; set; }
        public string LINNOM { get; set; }
        public string DESNOM { get; set; }
        public int CANTDEV { get; set; }
        public int EXISTENCIA { get; set; }
    }
}
