// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class impresion_manual_tarifarioResult
    {
        public string preart { get; set; }
        public string Arespe { get; set; }
        public string arref { get; set; }
        public double? prevlr { get; set; }
        public int cod_precio { get; set; }
        public string PreTipoItem { get; set; }
        public string CliNit { get; set; }
        public string CliNom { get; set; }
        public DateTime prefvt { get; set; }
        public string clicod { get; set; }
    }
}
