// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class IMPRIME_VACACIONESResult
    {
        public string novemp { get; set; }
        public string empNom { get; set; }
        public string empced { get; set; }
        public string novcon { get; set; }
        public string centro_costo { get; set; }
        public string novnom { get; set; }
        public decimal novdhc { get; set; }
        public decimal novdeb { get; set; }
        public string tipo_contrato { get; set; }
        public string cargo { get; set; }
        public DateTime novdisini { get; set; }
        public DateTime novdisfin { get; set; }
        public int dias_disfrute { get; set; }
        public DateTime novfregreso { get; set; }
        public decimal otras_bases { get; set; }
        public decimal ultimo_sueldo { get; set; }
        public int novdiascom { get; set; }
        public string novpuc { get; set; }
        public DateTime? novini { get; set; }
        public DateTime? novfin { get; set; }
        public int rompimiento { get; set; }
        public string Entidad { get; set; }
        public string empEmail { get; set; }
        public int NovDiaLiq { get; set; }
        public int NovDiaAcum { get; set; }
    }
}
