// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class IMPRIME_REQUISICIONResult
    {
        public string REQNRO { get; set; }
        public decimal REQCAN { get; set; }
        public string ARESPE { get; set; }
        public string REQELE { get; set; }
        public decimal REQID { get; set; }
        public DateTime? REQFEC { get; set; }
        public DateTime? ReqFecReq { get; set; }
        public string ReqObs { get; set; }
        public string ReqUsr { get; set; }
        public string ReqOT { get; set; }
        public int? ReqEst { get; set; }
        public string arref { get; set; }
        public string ardes { get; set; }
        public string armed { get; set; }
        public string NOMEMP { get; set; }
        public string CCONOM { get; set; }
        public string NOMARE { get; set; }
        public string DEPENDENCIA { get; set; }
        public string user_autoriza { get; set; }
        public string DETALLE_OT { get; set; }
        public string CLINOM { get; set; }
        public string nombre_centro { get; set; }
    }
}
