// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Ne_CalcularHoras2Result
    {
        public decimal? Tiempo { get; set; }
        public decimal? HO { get; set; }
        public decimal? RN { get; set; }
        public decimal? RND { get; set; }
        public decimal? RD { get; set; }
        public decimal? HED { get; set; }
        public decimal? HEN { get; set; }
        public decimal? HEDD { get; set; }
        public decimal? HEND { get; set; }
    }
}
