// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Ne_CalcularHorasResult
    {
        public int? Tiempo { get; set; }
        public int? HO { get; set; }
        public int? RN { get; set; }
        public int? RND { get; set; }
        public int? RD { get; set; }
        public int? HED { get; set; }
        public int? HEN { get; set; }
        public int? HEDD { get; set; }
        public int? HEND { get; set; }
    }
}
