// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Ne_HistorialTurnosResult
    {
        public string CodigoEmpleado { get; set; }
        public string Empleado { get; set; }
        public string FechaInicial { get; set; }
        public string HoraInicial { get; set; }
        public int? MargenIni { get; set; }
        public string FechaFinal { get; set; }
        public string HoraFinal { get; set; }
        public int? MargenFin { get; set; }
        public string Explicación { get; set; }
    }
}
