// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Ne_ObtenerCargoPorCodigoResult
    {
        public string delmrk { get; set; }
        public string cargocod { get; set; }
        public string cargoNom { get; set; }
        public decimal cargoSuelBas { get; set; }
        public string cargoFPago { get; set; }
        public string cargoCesantias { get; set; }
        public string cargoPension { get; set; }
        public string cargoEps { get; set; }
        public string cargoCCosto { get; set; }
        public int cargoturnos { get; set; }
        public string cargoCodSueldo { get; set; }
        public string cargoCodPrimas { get; set; }
        public string cargoCodVacaciones { get; set; }
        public string cargoCodIncapacidad { get; set; }
        public string cargoCodCesantias { get; set; }
        public string cargoCodIntCesantias { get; set; }
        public string cargoCodSubTrans { get; set; }
        public string cargoARP { get; set; }
        public string cargoCodRN { get; set; }
        public string cargoCodHED { get; set; }
        public string cargoCodHEN { get; set; }
        public string cargoCodHEFD { get; set; }
        public string cargoCodHEFN { get; set; }
        public string cargocodpen { get; set; }
        public string cargocodeps { get; set; }
        public string cargodomfer { get; set; }
        public string cargocodret { get; set; }
        public decimal cargoPorArp { get; set; }
        public string cargocodasal { get; set; }
        public string cargocodccf { get; set; }
        public string cargocodicbf { get; set; }
        public string cargocodsena { get; set; }
        public decimal cargoaporsal { get; set; }
        public decimal cargoaporpen { get; set; }
        public decimal cargoporccf { get; set; }
        public decimal cargoporicbf { get; set; }
        public decimal cargoporsena { get; set; }
        public string cargocodapen { get; set; }
        public string cargocodarp { get; set; }
        public string cargocodsalcia { get; set; }
        public string cargocodpencia { get; set; }
        public decimal cargoporsalcia { get; set; }
        public decimal cargoporpencia { get; set; }
        public string cargoccf { get; set; }
        public string cargocodfsp { get; set; }
        public decimal cargoporfsp { get; set; }
        public string cargocodcesantiasporpagar { get; set; }
        public decimal CargoAporSal2 { get; set; }
        public string CargoCodComi { get; set; }
        public string CargoCodBoni { get; set; }
        public decimal CargoAporPen2 { get; set; }
        public string CargoCodAsal2 { get; set; }
        public string CargoCodAPen2 { get; set; }
        public decimal cargoporsalcia2 { get; set; }
        public decimal cargoporpencia2 { get; set; }
        public string CargoCodsalcia2 { get; set; }
        public string cargocodpencia2 { get; set; }
        public string cargoVivienda { get; set; }
        public string cargoCodDFN { get; set; }
        public string CargoCuentaCCF { get; set; }
        public string CargoCuentaICBF { get; set; }
        public string CargoCuentaSENA { get; set; }
        public string CargoCuentaARP { get; set; }
        public decimal cargoTransporte { get; set; }
        public string cargoCodPrimaConvencional { get; set; }
        public string cargoCodPrimaVacacional { get; set; }
    }
}
