// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Ne_ObtenerTurnosEmpleadosPorFechaResult
    {
        public string Identificacion { get; set; }
        public string NombreEmp { get; set; }
        public string NombreCar { get; set; }
        public string Horario { get; set; }
        public string HorIniTur { get; set; }
        public string HorFinTur { get; set; }
        public string FechaEntrada { get; set; }
        public string HoraEntrada { get; set; }
        public string FechaSalida { get; set; }
        public string HoraSalida { get; set; }
        public byte Tolerancia { get; set; }
        public string Tardanza { get; set; }
        public string SalioTemprano { get; set; }
        public string HoraExtra { get; set; }
        public string TiempoTrabajado { get; set; }
        public string TiempoAsistido { get; set; }
        public string Duracio { get; set; }
        public string empcod { get; set; }
        public bool AutoExtra { get; set; }
        public int Id { get; set; }
        public string Novedad { get; set; }
        public string Cargo { get; set; }
        public string Area { get; set; }
        public string LlegadaAnt { get; set; }
        public string motivo { get; set; }
        public string TurExplicacion { get; set; }
        public bool AutorizarAnt { get; set; }
        public string codigotur { get; set; }
        public string Recargos { get; set; }
    }
}
