// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Ne_TurnosOrderByResult
    {
        public string empNom { get; set; }
        public string cargoNom { get; set; }
        public string FechaEntrada { get; set; }
        public string HoraEntrada { get; set; }
        public string FechaSalida { get; set; }
        public string HoraSalida { get; set; }
        public string Duracio { get; set; }
        public string empcod { get; set; }
        public string Hora_Extra { get; set; }
        public bool AutoExtra { get; set; }
    }
}
