// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AVConductores2Result
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string cedula { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string licencia { get; set; }
        public string categoria { get; set; }
        public DateTime? vigencia { get; set; }
    }
}
