// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AccGLMASTrasladoResult
    {
        public string Mascod { get; set; }
        public string Masdet { get; set; }
        public string Masdoc { get; set; }
        public DateTime? masfec { get; set; }
    }
}
