// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_Ausentismo_RangoResult
    {
        public int? Rango_Desde { get; set; }
        public int? Rango_Hasta { get; set; }
        public string Rango_Concepto { get; set; }
        public string conNom { get; set; }
        public decimal? Rango_Porcentaje { get; set; }
    }
}
