// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AFActivoSerialesResult
    {
        public int CodActivo { get; set; }
        public string Serial { get; set; }
        public DateTime Fecha_Adq { get; set; }
        public decimal tiemporest { get; set; }
        public string CodUbicacion { get; set; }
        public string Ubicacion { get; set; }
        public string CodArea { get; set; }
        public string Area { get; set; }
        public string CodResponsable { get; set; }
        public string Responsable { get; set; }
        public int? numEstado { get; set; }
        public string Estado { get; set; }
        public decimal AdicionesMejoras { get; set; }
        public decimal DepAcum { get; set; }
        public decimal Costohist { get; set; }
        public bool? seleccion { get; set; }
        public int idSerial { get; set; }
    }
}
