// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AFMantenimientoMaterialesResult
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal Cantidad { get; set; }
        public string Medida { get; set; }
        public decimal CostoCalculado { get; set; }
        public decimal Costo { get; set; }
    }
}
