// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AccglPucResult
    {
        public string glcod { get; set; }
        public string glnum { get; set; }
        public string glbal_tipo { get; set; }
        public bool? glcct_Chek { get; set; }
        public bool? glter_Chek { get; set; }
        public bool? glreqActivo_Chek { get; set; }
        public bool? Sel { get; set; }
    }
}
