// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AFAddMejorasActivoResult
    {
        public int CodActivo { get; set; }
        public int IdAddMejora { get; set; }
        public DateTime FechaAdd { get; set; }
        public string Observacion { get; set; }
        public string Responsable { get; set; }
        public decimal ValorAdd { get; set; }
        public int TiempoAdd { get; set; }
    }
}
