// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AGENDAResult
    {
        public DateTime Fecha { get; set; }
        public string Seguimiento { get; set; }
        public string Observaciones { get; set; }
        public string Cliente { get; set; }
        public string Contacto { get; set; }
        public decimal VlrAbono { get; set; }
        public DateTime FechaPago { get; set; }
        public DateTime nFecha { get; set; }
        public string Hora { get; set; }
        public int nId { get; set; }
        public string telefonos { get; set; }
    }
}
