// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ACPeriodoResult
    {
        public int Año { get; set; }
        public int Estado { get; set; }
        public int PCGA { get; set; }
        public int NIIF { get; set; }
    }
}
