// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AUIResult
    {
        public string codigo { get; set; }
        public string cuenta { get; set; }
        public decimal porc { get; set; }
        public decimal Iva { get; set; }
    }
}
