// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ActivosFijosResult
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal? Cantida { get; set; }
        public DateTime FechaAdquisicion { get; set; }
        public decimal? Costo { get; set; }
        public decimal? FaltaDep { get; set; }
        public decimal? AddMejoras { get; set; }
        public decimal? DepAcumMesAnt { get; set; }
        public decimal? DepMes { get; set; }
        public decimal? DepAcumMes { get; set; }
        public string Ubicacion { get; set; }
        public string Empleado { get; set; }
        public string Tipo { get; set; }
        public string Cuenta { get; set; }
        public string Ccosto { get; set; }
        public string EstadoUso { get; set; }
        public decimal? TiempoDepre { get; set; }
        public bool? seleccion { get; set; }
        public int tipo2 { get; set; }
        public int perte { get; set; }
        public string localizacion { get; set; }
    }
}
