// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AFActivoMantenimientoResult
    {
        public int CodActivo { get; set; }
        public int IdMantenimiento { get; set; }
        public string ManteNombre { get; set; }
        public string Modalidad { get; set; }
        public string FactorCondicional { get; set; }
    }
}
