// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_AsohofrucolResult
    {
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Proveedor { get; set; }
        public string Ciudad { get; set; }
        public string Departamento { get; set; }
        public decimal? Cantidad { get; set; }
        public string Medida { get; set; }
        public decimal? Costo { get; set; }
        public decimal? CostoTotal { get; set; }
        public decimal ValRetenido { get; set; }
        public string Linea { get; set; }
        public string Grupo { get; set; }
        public string Marca { get; set; }
    }
}
