// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_BonosResult
    {
        public string boncod { get; set; }
        public DateTime bonfec { get; set; }
        public string clinit { get; set; }
        public string clinom { get; set; }
        public decimal bonval { get; set; }
        public string Estado { get; set; }
    }
}
