// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class pa_ct_rpResult
    {
        public string delmrk { get; set; }
        public string cotnum { get; set; }
        public string cotcli { get; set; }
        public DateTime? cotfec { get; set; }
        public string cotdet { get; set; }
        public decimal? cotcan { get; set; }
        public int? cotiva { get; set; }
        public decimal? cottot { get; set; }
        public string cotest { get; set; }
        public string CotVen { get; set; }
        public int CotTip { get; set; }
        public string cotcondi { get; set; }
        public string vencod { get; set; }
        public string cotvali { get; set; }
        public string cotforpa { get; set; }
        public string cotgar { get; set; }
        public string cotna { get; set; }
        public decimal cotflete { get; set; }
        public decimal cotdcto { get; set; }
        public decimal cotrete { get; set; }
        public decimal cotTipoCambio { get; set; }
        public string cotCalifica { get; set; }
        public DateTime cotfecestado { get; set; }
        public string cotfactura { get; set; }
        public DateTime cotFecFactura { get; set; }
        public string cotescala { get; set; }
        public string cotusuario { get; set; }
        public string cotEstacion { get; set; }
        public string cotOT { get; set; }
        public DateTime cotFechaOT { get; set; }
        public string Solicitante { get; set; }
        public decimal Descuento { get; set; }
        public int DesdeOt { get; set; }
        public string numActaFinal { get; set; }
        public DateTime FechaRegistro { get; set; }
        public decimal? rentabilidad { get; set; }
        public int cotAiu { get; set; }
        public int cotIvaInc { get; set; }
        public string CotRemision { get; set; }
        public string CotFteFactura { get; set; }
        public int CodigoSolicitante { get; set; }
        public string CotTipMon { get; set; }
        public string CotPedido { get; set; }
        public int IsOrden { get; set; }
        public DateTime DateLastUpd { get; set; }
    }
}
