// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ClientesFinancResult
    {
        public string Codigo { get; set; }
        public string TipoDocumento { get; set; }
        public string NumDocumento { get; set; }
        public string TipoPersona { get; set; }
        public string RazonSocial { get; set; }
        public string PriApellido { get; set; }
        public string SegApellido { get; set; }
        public string PriNombre { get; set; }
        public string SegNombre { get; set; }
        public string RepLegal { get; set; }
        public string Cedula { get; set; }
        public string Contacto { get; set; }
        public string Cargo { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Fax { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string NumCuenta { get; set; }
        public string TipoCuenta { get; set; }
        public string Banco { get; set; }
        public string Disp_Sis { get; set; }
        public string Entidad { get; set; }
        public string Cual { get; set; }
        public string En_proceso { get; set; }
        public string Escala { get; set; }
        public string Dec_Auto { get; set; }
        public string CupoCred { get; set; }
        public string Saldo { get; set; }
        public string Ulti_Venta { get; set; }
        public string FechaIngreso { get; set; }
        public string Cred_Dias { get; set; }
        public string Puntos { get; set; }
        public string ReteFuente { get; set; }
        public string ReteIva { get; set; }
        public string ReteIca { get; set; }
        public string Gran_Contr { get; set; }
        public string TipoReg { get; set; }
        public string Vendedor { get; set; }
        public string Tipo_Cliente { get; set; }
        public string Cond_Comer { get; set; }
        public string Manual_tar { get; set; }
        public string Cuenta_Control { get; set; }
        public string Actividad { get; set; }
        public string DV { get; set; }
        public string estado { get; set; }
        public string Convenio { get; set; }
        public string FechaNacimiento { get; set; }
        public string RespatCli { get; set; }
        public string IngresoMensual { get; set; }
        public string EgresoMensual { get; set; }
        public string NivelEstudios { get; set; }
        public string PersonasCargo { get; set; }
        public string TipoContratoCli { get; set; }
        public string EstabilidadLaboral { get; set; }
        public string ActividadesCli { get; set; }
        public string EstadoCivil { get; set; }
        public string TipoVivienda { get; set; }
        public string HabitoPago { get; set; }
        public string Jailing { get; set; }
    }
}
