// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CargoEmpPerfilResult
    {
        public int Orden { get; set; }
        public string Texto { get; set; }
        public string Eliminar { get; set; }
    }
}
