// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CargosMedicoResult
    {
        public string CodigoCargo { get; set; }
        public string NombreCargo { get; set; }
        public decimal Id { get; set; }
    }
}
