// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CFG_DeterioroResult
    {
        public decimal Mes { get; set; }
        public decimal Periodo { get; set; }
        public string Documento { get; set; }
        public string Fuente { get; set; }
        public DateTime Fecha { get; set; }
    }
}
