// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CLIENTE_CARTERAResult
    {
        public string clicod { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string telefono { get; set; }
        public int cred { get; set; }
        public decimal cupo { get; set; }
        public string Pais { get; set; }
    }
}
