// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CalificacionProveedoresResult
    {
        public string ClCCodigo { get; set; }
        public string ClCConcepto { get; set; }
        public decimal ClCTasa { get; set; }
        public int ClCDias { get; set; }
    }
}
