// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CMICXPResult
    {
        public string NROFAC { get; set; }
        public string NROCXPIMP { get; set; }
        public decimal VLRIMP { get; set; }
        public DateTime? FECFAC { get; set; }
        public string CODPRO { get; set; }
        public string CCOSTO { get; set; }
    }
}
