// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CiudadDptoPaisResult
    {
        public string ciucod { get; set; }
        public string codDpto { get; set; }
        public string CodPais { get; set; }
    }
}
