// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CAlculoPrioridadesResult
    {
        public int CodigoEquipo { get; set; }
        public string NombreEquipo { get; set; }
        public string nombreMante { get; set; }
        public string tipoMantenimiento { get; set; }
    }
}
