// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ConceptosTerResult
    {
        public string codigo { get; set; }
        public string cuenta { get; set; }
        public string detalle { get; set; }
        public decimal Debito { get; set; }
        public decimal Credito { get; set; }
        public string CCOSTO { get; set; }
        public string CCONOM { get; set; }
        public string CodTercero { get; set; }
        public string TERNOM { get; set; }
        public string NumOt { get; set; }
        public long ID { get; set; }
    }
}
