// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ConfigEmailResult
    {
        public string remitente { get; set; }
        public string password { get; set; }
        public string servidor { get; set; }
        public string puerto { get; set; }
    }
}
