// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ContDescripRegResult
    {
        public string Clase { get; set; }
        public string Grupo { get; set; }
        public string Mayor { get; set; }
        public string Subcuenta { get; set; }
        public string Auxiliar { get; set; }
        public string Ccosto { get; set; }
        public string Tercero { get; set; }
        public string Documento { get; set; }
        public DateTime? Fecha { get; set; }
        public string Fuente { get; set; }
        public decimal? Debe { get; set; }
        public decimal? Haber { get; set; }
        public decimal? TotalDebe { get; set; }
        public decimal? TotalHaber { get; set; }
        public string Estacion { get; set; }
        public DateTime? FechaDoc { get; set; }
        public string Usuario { get; set; }
    }
}
