// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CancelacionFacturasVentaResult
    {
        public bool? Sel { get; set; }
        public string NumeroFactura { get; set; }
        public string FechaFactura { get; set; }
        public string VencimientoFactura { get; set; }
        public int? DiasVencido { get; set; }
        public decimal ValorFactura { get; set; }
        public decimal SubTotalFactura { get; set; }
        public decimal? DescuentoFactura { get; set; }
        public decimal? ReteFuenteFactura { get; set; }
        public decimal? ReteGarantiaFactura { get; set; }
        public decimal? ReteIVAFactura { get; set; }
        public decimal? ReteIcaFactura { get; set; }
        public decimal? RetencionFactura { get; set; }
        public decimal? IVAFactura { get; set; }
        public decimal? AbonoFactura { get; set; }
        public decimal? Puntos { get; set; }
        public decimal SaldoFactura { get; set; }
        public decimal? SaldoMonedaAct { get; set; }
        public decimal AnticipoFactura { get; set; }
        public string TipoFactura { get; set; }
        public string TipoCliente { get; set; }
        public string NombreTipocliente { get; set; }
        public string CodigoCliente { get; set; }
        public string NitCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Nota { get; set; }
        public DateTime? FechaPago { get; set; }
        public int? Estado { get; set; }
        public int? Cancelada { get; set; }
        public string Concepto { get; set; }
        public bool? Anulada { get; set; }
        public int? Causado { get; set; }
        public string CentroCosto { get; set; }
        public string EscalaPrecio { get; set; }
        public string Vendedor { get; set; }
        public decimal? DescuentoAutorizado { get; set; }
        public decimal? TasaCambio { get; set; }
        public decimal? TasaCambioTemp { get; set; }
        public decimal ValorInteres { get; set; }
        public decimal ValorMora { get; set; }
        public decimal ValorInteresTemp { get; set; }
        public decimal AbonoTemp { get; set; }
        public decimal DescuentoTemp { get; set; }
        public decimal GarantiaTemp { get; set; }
        public decimal ReteICATemp { get; set; }
        public decimal AnticipoTemp { get; set; }
        public decimal ReteFuenteTemp { get; set; }
        public decimal ReteIVATemp { get; set; }
        public decimal SaldoFacturaTemp { get; set; }
        public decimal RetencionesTemp { get; set; }
        public string Factura { get; set; }
        public int SwValor { get; set; }
        public decimal RcDescuento { get; set; }
        public decimal RcRTFTE { get; set; }
        public decimal RcRTICA { get; set; }
        public decimal RcRTIVA { get; set; }
        public decimal RcRTGarantia { get; set; }
        public decimal RcAbono { get; set; }
        public decimal RcSaldo { get; set; }
        public decimal RcAnticipo { get; set; }
        public decimal SaldoReal { get; set; }
    }
}
