// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CITASResult
    {
        public int ID { get; set; }
        public string Recurso { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
    }
}
