// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CorreoMantenimientoResult
    {
        public string Enviar { get; set; }
        public string Correos { get; set; }
        public string Subjetc { get; set; }
        public string Boddy { get; set; }
    }
}
