// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_COTI_SEGUIMResult
    {
        public DateTime Fecha { get; set; }
        public string Seguimiento { get; set; }
        public string Observaciones { get; set; }
        public string Contacto { get; set; }
        public decimal VlrAbono { get; set; }
        public DateTime? FechaPago { get; set; }
        public DateTime? nFecha { get; set; }
        public string Hora { get; set; }
        public bool? Agenda { get; set; }
        public string Usuario { get; set; }
        public string EstAdd { get; set; }
        public DateTime FecAdd { get; set; }
        public int nId { get; set; }
    }
}
