// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ConfigAutorizacionResult
    {
        public string Usuario { get; set; }
        public string Empleado { get; set; }
        public decimal Valor { get; set; }
        public string CodUsuario { get; set; }
        public decimal id { get; set; }
        public string RUTA { get; set; }
    }
}
