// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ClientesFac_DBResult
    {
        public string clicod { get; set; }
        public string clinit { get; set; }
        public string clinom { get; set; }
        public bool facturable { get; set; }
        public string SubCentroCosto { get; set; }
        public string Codscco { get; set; }
    }
}
