// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CambioPreciosResult
    {
        public string Codigo { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public string Medida { get; set; }
        public decimal CostoUltCompra { get; set; }
        public decimal Costo { get; set; }
        public decimal IVA { get; set; }
        public decimal Porcentaje1 { get; set; }
        public decimal Escala1 { get; set; }
        public decimal Porcentaje2 { get; set; }
        public decimal Escala2 { get; set; }
        public decimal Porcentaje3 { get; set; }
        public decimal Escala3 { get; set; }
        public decimal Porcentaje4 { get; set; }
        public decimal Escala4 { get; set; }
        public decimal PorMinimo { get; set; }
        public decimal Minimo { get; set; }
        public bool? UsoPP { get; set; }
        public decimal arPorDesc1 { get; set; }
        public decimal arPorDesc2 { get; set; }
        public decimal arPorDesc3 { get; set; }
        public decimal arPorDesc4 { get; set; }
    }
}
