// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ConfigImportResult
    {
        public string CodigoSubcentro { get; set; }
        public string NombreSubcentro { get; set; }
        public string CodigoXmart { get; set; }
    }
}
