// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_CheckIngresosEmpleadoResult
    {
        public int TurId { get; set; }
        public string TurEmpleado { get; set; }
        public DateTime TurFechaIni { get; set; }
        public string TurHoraIni { get; set; }
        public DateTime TurFechaFin { get; set; }
        public string TurHoraFin { get; set; }
        public int TurEstado { get; set; }
        public string TurTipo { get; set; }
        public string TurBarraSocio { get; set; }
        public string TurSerial { get; set; }
        public int TurDuracion { get; set; }
        public string TurExplicacion { get; set; }
        public int HorTur { get; set; }
        public DateTime? TurFechaRegistro { get; set; }
        public string horario { get; set; }
        public string tardanza { get; set; }
        public string salida_temprano { get; set; }
        public string hora_extra { get; set; }
        public string Tiempo_trabajado { get; set; }
        public bool fin_semana { get; set; }
        public bool feriado { get; set; }
        public string centro_costo { get; set; }
        public string CodigoTur { get; set; }
        public byte Tolerancia { get; set; }
        public string horaIniTur { get; set; }
        public string horaFinTur { get; set; }
        public string tiempo_asistido { get; set; }
        public bool semana { get; set; }
        public bool AutoExtra { get; set; }
        public string Novedad { get; set; }
        public string Llegada_ant { get; set; }
        public string motivo { get; set; }
        public bool AutorizarAnt { get; set; }
        public string Recargos { get; set; }
    }
}
