// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_DevolucionVenResult
    {
        public string codigo_vendedor { get; set; }
        public decimal? devolucion { get; set; }
    }
}
