// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_DIVAResult
    {
        public string CODIGO { get; set; }
        public string MASCOD { get; set; }
        public decimal Valor { get; set; }
    }
}
