// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_DeprecicacionResult
    {
        public decimal panMes { get; set; }
        public string paames { get; set; }
        public decimal paaaño { get; set; }
        public string padocumento { get; set; }
        public string Fuente { get; set; }
        public string paFuente { get; set; }
    }
}
