// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_DetalleCContabilidadResult
    {
        public string Documento { get; set; }
        public DateTime? Fecha { get; set; }
        public string Detalle { get; set; }
        public decimal? Débito { get; set; }
        public decimal? Crédito { get; set; }
        public decimal Saldo { get; set; }
    }
}
