// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_DepreActivosFijosResult
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string TipoActivo { get; set; }
        public decimal Cantidad { get; set; }
        public DateTime FechaAdqui { get; set; }
        public decimal CostoHunitario { get; set; }
        public decimal TiempRest { get; set; }
        public string Ubicacion { get; set; }
        public string Responsable { get; set; }
        public int Uso { get; set; }
        public string Ccosto { get; set; }
        public string DescripcionBien { get; set; }
        public int UsoDelBien { get; set; }
        public decimal VlrNetoLib { get; set; }
        public DateTime FecAvaluo { get; set; }
        public decimal vlrAvaluo { get; set; }
        public decimal Provision { get; set; }
        public decimal Valorizacion { get; set; }
        public int RepGrupo { get; set; }
        public string GravJuridico { get; set; }
        public DateTime FecUltPagImp { get; set; }
        public string DescCituaJuri { get; set; }
        public decimal AmortiAgot { get; set; }
        public string Poliza { get; set; }
        public decimal TiempoDepre { get; set; }
        public int Clasificacion { get; set; }
        public decimal AddMejoras { get; set; }
        public decimal? DepDepAcumAnt { get; set; }
        public decimal ValorRenta { get; set; }
        public string MedidaRenta { get; set; }
        public decimal Escala1 { get; set; }
        public decimal Escala2 { get; set; }
        public decimal Escala3 { get; set; }
        public decimal Escala4 { get; set; }
        public bool Seriales { get; set; }
        public string area { get; set; }
        public int Estado { get; set; }
        public int TvuLocalCap { get; set; }
        public int TvuLNiif { get; set; }
        public string CodProveedor { get; set; }
        public int ReqMante { get; set; }
        public decimal Iva { get; set; }
        public string Localizacion { get; set; }
        public decimal DprVal { get; set; }
        public decimal CostoAvaluado { get; set; }
        public decimal DepreNiff { get; set; }
        public decimal Deterioro { get; set; }
        public string preoperacional { get; set; }
        public string Liquidarpor { get; set; }
        public int TCombustible { get; set; }
    }
}
