// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_DatosEmpresaResult
    {
        public string Nombre { get; set; }
        public string Nit { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Regimen { get; set; }
        public string Resolucion { get; set; }
        public string ObservacionFactura { get; set; }
        public string logo { get; set; }
        public string TFactura { get; set; }
    }
}
