// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_Documentos_OTResult
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string version { get; set; }
        public DateTime vigencia { get; set; }
        public string tipoFormato { get; set; }
    }
}
