// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_DependenciaResult
    {
        public string delmrk { get; set; }
        public string depcod { get; set; }
        public string depnom { get; set; }
        public string deppuc { get; set; }
        public string depcos { get; set; }
        public string deping { get; set; }
        public string invgrv { get; set; }
        public string invexc { get; set; }
        public string invext { get; set; }
        public string cosgrv { get; set; }
        public string cosexc { get; set; }
        public string cosext { get; set; }
        public string inggrv { get; set; }
        public string ingexc { get; set; }
        public string ingext { get; set; }
        public string DepCre { get; set; }
        public string DepPOS { get; set; }
        public string DepResCre { get; set; }
        public string DepResPOS { get; set; }
        public string DepPreCre { get; set; }
        public string DepPrePOS { get; set; }
        public string DOConsImp { get; set; }
        public string DOConsExp { get; set; }
        public string EgreCons { get; set; }
        public string ReciCons { get; set; }
        public string PreImp { get; set; }
        public string PreExp { get; set; }
        public int Farmacia { get; set; }
        public string Tipo { get; set; }
        public string DEVOLUCIONES { get; set; }
        public string DepDir { get; set; }
        public int depcoc { get; set; }
        public int depmesas { get; set; }
        public string TranCons { get; set; }
        public string NDBCons { get; set; }
        public string NCRCons { get; set; }
        public string FactCons { get; set; }
        public string PreFact { get; set; }
        public string DepCaja { get; set; }
        public string depcCosto { get; set; }
        public string deptel { get; set; }
        public string depObser { get; set; }
        public int DepConsignacion { get; set; }
        public int IDresolucionFR { get; set; }
        public int IDresolucionCT { get; set; }
        public string ModifiedByUser { get; set; }
        public int depEst { get; set; }
        public string DepResDocSop { get; set; }
        public int IDresolucionDocSop { get; set; }
        public string DepPreDocSop { get; set; }
        public string DepDocSop { get; set; }
    }
}
