// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_EmailResult
    {
        public string servidor { get; set; }
        public string remitente { get; set; }
        public bool ssl { get; set; }
        public bool autenticacion { get; set; }
        public string password { get; set; }
        public string puerto { get; set; }
        public string asunto { get; set; }
        public string Cuerpo { get; set; }
        public int NotifHoras { get; set; }
        public int NotifKilom { get; set; }
        public int NotifMov { get; set; }
        public int NotifDias { get; set; }
        public string Modulo { get; set; }
        public int mailId { get; set; }
        public string Replyto { get; set; }
    }
}
