// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ExcepcionesDeterioroResult
    {
        public string Documento { get; set; }
        public string Cliente { get; set; }
        public string Fecha { get; set; }
        public string Vence { get; set; }
        public string DiasVen { get; set; }
    }
}
