// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ExceptionsResult
    {
        public string MENSAJE { get; set; }
        public int BOTON { get; set; }
        public int ICONO { get; set; }
    }
}
