// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ExcepcionesHorariosTurnosResult
    {
        public string CodExcepcion { get; set; }
        public string CodEmpleado { get; set; }
        public string CedulaEmpleado { get; set; }
        public string Empleado { get; set; }
        public bool? Sel { get; set; }
    }
}
