// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_EDITCARTASResult
    {
        public int Cod_Carta { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
    }
}
