// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_FlujoEfectivoRecResult
    {
        public string Movimiento { get; set; }
        public double? Total { get; set; }
        public string llaveCab { get; set; }
    }
}
