// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_FechasEspecialesResult
    {
        public string CodigoCliente { get; set; }
        public string TipoEvento { get; set; }
        public string Descripcion { get; set; }
        public int Mes { get; set; }
        public int Dia { get; set; }
    }
}
