// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_FormatoClienteResult
    {
        public string FechaSolicitud { get; set; }
        public bool? PersonaJuridica { get; set; }
        public bool? PersonaNatural { get; set; }
        public bool? RegimenComun { get; set; }
        public bool? RegimenSimplificado { get; set; }
        public bool? RegimenEspecial { get; set; }
        public string RazonSocial { get; set; }
        public string NITCC { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Departamento { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string RepLegal { get; set; }
        public string CedulaRepLegal { get; set; }
        public string Contacto { get; set; }
        public string Cargo { get; set; }
        public bool? SiReteFuente { get; set; }
        public bool? NoReteFuente { get; set; }
        public bool? SiGranCont { get; set; }
        public bool? NoGranCont { get; set; }
        public bool? SiReteIva { get; set; }
        public bool? NoReteIva { get; set; }
        public bool? SiReteIca { get; set; }
        public bool? NoReteIca { get; set; }
        public string ActividadEcono { get; set; }
        public string CIIU { get; set; }
        public decimal TarifaICA { get; set; }
        public string Banco { get; set; }
        public string NumeroCuenta { get; set; }
        public bool? CtaCorriente { get; set; }
        public bool? CtaAhorros { get; set; }
        public string NOMBREREF { get; set; }
        public string TELEFONOREF { get; set; }
        public string NOMBREREF2 { get; set; }
        public string TELEFONOREF2 { get; set; }
        public string NOMBREREF3 { get; set; }
        public string TELEFONOREF3 { get; set; }
        public string NOMBREREFBAN { get; set; }
        public string TELEFONOREFBAN { get; set; }
        public string NOMBREREFBAN2 { get; set; }
        public string TELEFONOREFBAN2 { get; set; }
        public string NOMBREREFBAN3 { get; set; }
        public string TELEFONOREFBAN3 { get; set; }
    }
}
