// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_FormulasResult
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal Cantidad { get; set; }
        [Column("Unidad de medida")]
        public string Unidaddemedida { get; set; }
        public decimal Costo { get; set; }
        public int Precio { get; set; }
        public decimal? Escala1 { get; set; }
        public decimal? Escala2 { get; set; }
        public decimal? Escala3 { get; set; }
        public decimal? Escala4 { get; set; }
        public string IdItem { get; set; }
        public decimal? CostoTotal { get; set; }
        public bool ivamayor { get; set; }
    }
}
