// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_GestionChequesResult
    {
        public string Documento { get; set; }
        public string Cuenta { get; set; }
        public string Fecha { get; set; }
        public string Tercero { get; set; }
        public double? Valor { get; set; }
        public string Cheque { get; set; }
    }
}
