// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_GrillasPlantillaPMResult
    {
        public int? Id { get; set; }
        public string Seleccion { get; set; }
        public string CodigoEquipo { get; set; }
        public string IdMto { get; set; }
        public string CodigoMto { get; set; }
        public string Serial { get; set; }
        public string NombreEq { get; set; }
        public string NombreMto { get; set; }
        public decimal? LecturaActual { get; set; }
        public string Tipo { get; set; }
        public string CndicionalEquipo { get; set; }
        public decimal? Acumulado { get; set; }
        public string Color { get; set; }
        public string OT { get; set; }
    }
}
