// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_GetUsuarioResult
    {
        public string delmrk { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public decimal Cajero { get; set; }
        public string Tipo { get; set; }
        public int Aprobar { get; set; }
        public decimal monto { get; set; }
        public string Area { get; set; }
        public string cooCosto { get; set; }
        public string CodEmpleado { get; set; }
        public byte[] Clave { get; set; }
        public int UsarAPP { get; set; }
        public string UserDep { get; set; }
        public int UserCliente { get; set; }
        public decimal id { get; set; }
        public int ConfigTProv { get; set; }
        public string UserV { get; set; }
        public string Password { get; set; }
    }
}
