// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_GetTurnosResult
    {
        public string turhoraini { get; set; }
        public string turhorafin { get; set; }
        public int? tolerancia { get; set; }
        public string turCodigo { get; set; }
        public string TurHoraIniSab { get; set; }
        public string TurHoraFinSab { get; set; }
        public string TurHoraIniDom { get; set; }
        public string TurHoraFinDom { get; set; }
        public decimal TurDescanso { get; set; }
    }
}
