// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_GLDBUResult
    {
        public string Tabla { get; set; }
        public string Createby { get; set; }
        public string Date { get; set; }
        public string Module { get; set; }
        public string Project { get; set; }
        public string Purpose { get; set; }
        public string Relatedtables { get; set; }
        public int id { get; set; }
    }
}
