// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_GetCajaMenorPUCResult
    {
        public string ContraPartida { get; set; }
        public string Responsable { get; set; }
        public decimal Monto { get; set; }
    }
}
