// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_GetVehiculosResult
    {
        public string Placa { get; set; }
        public string Modelo { get; set; }
        public string Cilindraje { get; set; }
        public string chasis { get; set; }
        public string NroMotor { get; set; }
        public string TipoCombustible { get; set; }
        public string Color { get; set; }
        public string Marca { get; set; }
        public string Linea { get; set; }
        public string Empresa { get; set; }
        public string Propietario { get; set; }
        public string ConseRunt { get; set; }
        public string TipoServicio { get; set; }
        public string Clase { get; set; }
        public string TelPropietario { get; set; }
        public string Aseguradora1 { get; set; }
        public string poliza1 { get; set; }
        public DateTime? vence1 { get; set; }
        public decimal TipoPoliza { get; set; }
        public string Aseguradora2 { get; set; }
        public string poliza2 { get; set; }
        public DateTime? vence2 { get; set; }
        public string TarOpe { get; set; }
        public DateTime vTarOpe { get; set; }
        public int vSoatID { get; set; }
        public int vEgasID { get; set; }
        public int vCrtmID { get; set; }
        public int vPoliza1ID { get; set; }
        public int vPoliza2ID { get; set; }
    }
}
