// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_HojaVidaMttoResult
    {
        public int CodActivo { get; set; }
        public string CodActivoString { get; set; }
        public string Nombre { get; set; }
        public decimal VlrMejoras { get; set; }
        public decimal TiempoDep { get; set; }
        public string dprcodact { get; set; }
        public string nomare { get; set; }
    }
}
