// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_HistEjeMtoResult
    {
        public string Mantenimiento { get; set; }
        public string Tipo { get; set; }
        public string LecturaEjec { get; set; }
        public DateTime FechaEje { get; set; }
        public DateTime FechaProgEjec { get; set; }
        public DateTime FechaTerminacion { get; set; }
        public string Observaciones { get; set; }
        public string estadoFinal { get; set; }
    }
}
