// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_HistorialMttoResult
    {
        public string ordnro { get; set; }
        public string DPRCODACT { get; set; }
        public DateTime ORDFEC { get; set; }
        public string TRANOM { get; set; }
        public string ORDNOM { get; set; }
        public string TERNOM { get; set; }
        public string DIAGPRELIMINAR { get; set; }
        public string DIAGTECNICO { get; set; }
        public string SOLUCIONAPLICADA { get; set; }
        public DateTime FECHACIERRE { get; set; }
        public string NROFACT { get; set; }
        public DateTime FECHAFACT { get; set; }
        public decimal VLRFAC { get; set; }
    }
}
