// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Pa_HeaderCicloRetornoResult
    {
        public string nroOT { get; set; }
        public DateTime ordFec { get; set; }
        public DateTime FechaCierre { get; set; }
        public string Cotnum { get; set; }
        public DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
        public decimal IVA { get; set; }
        public decimal? totality { get; set; }
        public string clienteOT { get; set; }
        public string subcconom { get; set; }
        public string descripcion { get; set; }
        public decimal CostoPres { get; set; }
        public decimal CostoReal { get; set; }
        public decimal? rentPres { get; set; }
        public decimal? rentReal { get; set; }
        public decimal optReal { get; set; }
        public DateTime FechaEntrega { get; set; }
        public int? diasTrans { get; set; }
        public string NroFact { get; set; }
        public DateTime FechaFact { get; set; }
        public decimal anticipo { get; set; }
        public decimal VlrFac { get; set; }
        public string Recibo { get; set; }
        public DateTime FechaRecibo { get; set; }
        public string responsable { get; set; }
        public string interventor { get; set; }
        public string estado { get; set; }
        public string color { get; set; }
        public string clicod { get; set; }
        public string subcco { get; set; }
        public string CodigoActivo { get; set; }
        public decimal otros { get; set; }
    }
}
