// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_IndicadoresVendedorResult
    {
        public string vencod { get; set; }
        public string Identificación { get; set; }
        public string Nombre { get; set; }
        public decimal PresupuestoAnual { get; set; }
        public decimal MacuPresupuestado { get; set; }
        public decimal MacuEjecutado { get; set; }
        public decimal? MacuVariacion { get; set; }
        public decimal MesPresupuestado { get; set; }
        public decimal MesEjecutado { get; set; }
        public decimal? MesVariacion { get; set; }
        public decimal? Ejecucion { get; set; }
        public decimal? Variacion { get; set; }
        public decimal? Porcentaje { get; set; }
        public decimal? DiaPresupuestado { get; set; }
        public decimal DiaEjecutado { get; set; }
        public decimal? DiaVariacion { get; set; }
    }
}
