// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_IndicadoresClientesResult
    {
        public int? Activos { get; set; }
        public int? Potenciales { get; set; }
        public int? Retirados { get; set; }
    }
}
