// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_INV_GL_CFGResult
    {
        public string valiOfer { get; set; }
        public string garantia { get; set; }
        public string formapago { get; set; }
        public string condComerciales { get; set; }
        public string notaAclaratoria { get; set; }
    }
}
