// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_Insertion_FailResult
    {
        public string usuario { get; set; }
        public string ReferenciaProducto { get; set; }
        public string Details { get; set; }
    }
}
