// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ImpNominaEmpResult
    {
        public string NomCod { get; set; }
        public string NomNomb { get; set; }
        public int Dias { get; set; }
        public DateTime Fecha { get; set; }
    }
}
