// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_KardexConsolidadoResult
    {
        public string Código { get; set; }
        public string Artículo { get; set; }
        public string Referencia { get; set; }
        public string Medida { get; set; }
        [Column("Cantidad Inicial")]
        public decimal? CantidadInicial { get; set; }
        [Column("Costo Inicial")]
        public decimal? CostoInicial { get; set; }
        [Column("Cantidad Entrada")]
        public decimal? CantidadEntrada { get; set; }
        [Column("Costo Entrada")]
        public decimal? CostoEntrada { get; set; }
        [Column("Cantidad Salida")]
        public decimal? CantidadSalida { get; set; }
        [Column("Costo Salida")]
        public decimal? CostoSalida { get; set; }
        [Column("Cantidad Final")]
        public decimal? CantidadFinal { get; set; }
        [Column("Costo Final")]
        public decimal? CostoFinal { get; set; }
        public string Cuenta { get; set; }
        public string Marca { get; set; }
        public string Linea { get; set; }
        public string Grupo { get; set; }
        public string Dependencia { get; set; }
    }
}
