// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_logProcesosResult
    {
        public string TIPOCONCEPTO { get; set; }
        public string CONCEPTO { get; set; }
        public string DOCUMENTO { get; set; }
        public string AUTORIZADO { get; set; }
        public string USUARIO { get; set; }
        public string ESTACION { get; set; }
        public DateTime FECHA { get; set; }
        public string ACCION { get; set; }
        public string reatip { get; set; }
        public string JUSTIFICACION { get; set; }
    }
}
