// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ModelosContablesResult
    {
        public string CodigoDet { get; set; }
        public string Nombre { get; set; }
        public string CuentaDet { get; set; }
        public string NombreCuenta { get; set; }
        public int? Debito { get; set; }
        public int? Credito { get; set; }
        public string Tipo { get; set; }
        public string CampoOrden { get; set; }
        public string Grupo { get; set; }
    }
}
