// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_MtoSaldosIniMantenimientosResult
    {
        public int Id { get; set; }
        public string CodEquipo { get; set; }
        public string Serial { get; set; }
        public string NombreEquipo { get; set; }
        public string LectFinal { get; set; }
    }
}
