// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_MailRecepcionResult
    {
        public string remitente { get; set; }
        public string destinatario { get; set; }
        public string emails { get; set; }
        public DateTime fecha { get; set; }
        public string asunto { get; set; }
        public string mensaje { get; set; }
        public string adjunto { get; set; }
        public string error { get; set; }
    }
}
