// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_MttoConfigResult
    {
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal AcumuladoK { get; set; }
        public decimal AcumuladoH { get; set; }
        public int AcumuladoM { get; set; }
        public DateTime AcumuladoF { get; set; }
        public string TipoMovimiento { get; set; }
        public DateTime Fecha { get; set; }
        public decimal Lectura { get; set; }
        public string TipoMantenimiento { get; set; }
    }
}
