// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_Manual_Funciones_Periodo_RHResult
    {
        public int? indice { get; set; }
        public string item { get; set; }
        public string texto { get; set; }
        public int id { get; set; }
    }
}
