// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_NovFjsResult
    {
        public string Cedula { get; set; }
        public string Empleado { get; set; }
        public string TipoNomina { get; set; }
        public string TipoConcepto { get; set; }
        public string TipoCobro { get; set; }
        public string Concepto { get; set; }
        public decimal Valor { get; set; }
        public int ID { get; set; }
        public string CodConcepto { get; set; }
        public string CodEmpleado { get; set; }
        public int TCont { get; set; }
        public int TCobro { get; set; }
        public decimal ValorIBC { get; set; }
        public decimal Monto { get; set; }
        public decimal Saldo { get; set; }
        public DateTime FecIni { get; set; }
        public DateTime FecFin { get; set; }
        public int Forma { get; set; }
        public string CodTercero { get; set; }
        public string ternom { get; set; }
        public string Estado { get; set; }
        public int AplicarEn { get; set; }
    }
}
