// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_NE_Manual_Funciones_CargoResult
    {
        public int Indice { get; set; }
        public string Titulo { get; set; }
        public string Boton { get; set; }
        public int modificado { get; set; }
        public string Texto { get; set; }
        public int? Id { get; set; }
    }
}
