// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_NtConfigMailResult
    {
        public int Id { get; set; }
        public string eMail { get; set; }
        public string ContraseñaMail { get; set; }
        public string Host { get; set; }
        public int Puerto { get; set; }
        public string UsuarioServer { get; set; }
        public string ContraseñaServer { get; set; }
        public bool Ssl { get; set; }
    }
}
