// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_neSuspensionResult
    {
        public string CodigoEmpleado { get; set; }
        public DateTime FechaEvento { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public string CodigoMedidaCorrectiva { get; set; }
        public int Cantidad { get; set; }
        public string Tiempo { get; set; }
        public string CodigoFalta { get; set; }
        public string Observacion { get; set; }
        public int? Estado { get; set; }
        public DateTime FechaRegistro { get; set; }
    }
}
