// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_NtEnviosMailsResult
    {
        public int Id { get; set; }
        public DateTime FechaEnvio { get; set; }
    }
}
