// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_nePQRClResult
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Tercero { get; set; }
        [Column("Reportado por")]
        public string Reportadopor { get; set; }
        public string proceso { get; set; }
        public string empnom { get; set; }
        [Column("Tipo de Reseña")]
        public string TipodeReseña { get; set; }
        [Column("Situacion no Conforme")]
        public string SituacionnoConforme { get; set; }
        [Column("Descripción de la Situación")]
        public string DescripcióndelaSituación { get; set; }
        [Column("Causa 1")]
        public string Causa1 { get; set; }
        [Column("Causa 2")]
        public string Causa2 { get; set; }
        [Column("Causa 3")]
        public string Causa3 { get; set; }
        [Column("Causa 4")]
        public string Causa4 { get; set; }
        [Column("Causa 5")]
        public string Causa5 { get; set; }
        public string Correccion { get; set; }
        [Column("Acción Correctiva")]
        public string AcciónCorrectiva { get; set; }
        [Column("Fecha Recomend")]
        public DateTime FechaRecomend { get; set; }
        [Column("Fecha de Seguimiento")]
        public DateTime FechadeSeguimiento { get; set; }
        [Column("Fecha de Cierre")]
        public DateTime FechadeCierre { get; set; }
        [Column("Verificado por")]
        public string Verificadopor { get; set; }
        public string Estado { get; set; }
        [Column("Evidencia de Cumplimiento")]
        public string EvidenciadeCumplimiento { get; set; }
        public string Eficacia { get; set; }
        public string Observaciones { get; set; }
        public string Etiquetas { get; set; }
        [Column("Nro. Referencia")]
        public string NroReferencia { get; set; }
        [Column("SubCentro Costo")]
        public string SubCentroCosto { get; set; }
        public string Ciudad { get; set; }
    }
}
