// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_nePermisoResult
    {
        public string CodigoEmpleado { get; set; }
        public DateTime FechaEvento { get; set; }
        public DateTime FechaRegistro { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public string CodigoMedidaCorrectiva { get; set; }
        public int? Estado { get; set; }
        public string Observacion { get; set; }
        public string CodigoFalta { get; set; }
        public DateTime horaini { get; set; }
        public DateTime horafin { get; set; }
        public int Reingresa { get; set; }
    }
}
