// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_neReclamoResult
    {
        public string CodigoEmpleado { get; set; }
        public DateTime FechaInicio { get; set; }
        public string Observacion2 { get; set; }
        public DateTime FechaEvento { get; set; }
        public string Observacion3 { get; set; }
        public string Observacion { get; set; }
        public string CodigoEmpleado2 { get; set; }
        public int? Estado { get; set; }
    }
}
