// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_NtNotificacionesResult
    {
        public int Id { get; set; }
        public string IdUsuarios { get; set; }
        public string Procedencias { get; set; }
        public string Descripcion { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public int PeriodicidadNoti { get; set; }
        public int TipoPeriodicidadNoti { get; set; }
        public string Color { get; set; }
        public int Prioridad { get; set; }
        public bool Sonido { get; set; }
        public bool ViaMail { get; set; }
        public int PeriodicidadMail { get; set; }
        public int TipoPeriodicidadMail { get; set; }
        public string DestinatariosMail { get; set; }
        public string CuerpoMail { get; set; }
        public string FirmaMail { get; set; }
        public int delmrk { get; set; }
    }
}
