// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_Ordenes_PermisosResult
    {
        public string ordNro { get; set; }
        public string ordNom { get; set; }
        public DateTime ordFec { get; set; }
        public DateTime ordFecLiq { get; set; }
        public string ordCli { get; set; }
        public string ordCCO { get; set; }
        public string OrdTipOrden { get; set; }
        public string ordEst { get; set; }
    }
}
