// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_OrdenesResult
    {
        public string ordnro { get; set; }
        public string ordcli { get; set; }
        public DateTime ordFec { get; set; }
    }
}
