// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_OTROSEST_PROResult
    {
        public string dir_est { get; set; }
        public string ciu_est { get; set; }
        public string pais_est { get; set; }
        public string codigo_est { get; set; }
        public string ciudad { get; set; }
        public string pais { get; set; }
    }
}
