// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_OrdenesIMResult
    {
        public string moving { get; set; }
        public string glnum { get; set; }
        public decimal? movhbr { get; set; }
        public decimal? movdeb { get; set; }
    }
}
