// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_OrdenesIManteResult
    {
        public int? Codigo { get; set; }
        public string Equipo { get; set; }
        public string Nombre { get; set; }
        public string Mantenimiento { get; set; }
        public string Responsable { get; set; }
        public DateTime Fecha { get; set; }
    }
}
