// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ObtenerAusentismosResult
    {
        public string CodigoEmpleado { get; set; }
        public string Novedad { get; set; }
    }
}
