// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_OpcionPagosResult
    {
        public bool? Selec { get; set; }
        public string Factura { get; set; }
        public string Causacion { get; set; }
        public DateTime? Fecha { get; set; }
        public decimal Valor { get; set; }
        public int ReteCREE { get; set; }
        public int ReteFte { get; set; }
        public int ReteICA { get; set; }
        public int ReteIVA { get; set; }
        public decimal Abonos { get; set; }
        public decimal Anticipos { get; set; }
        public decimal Saldo { get; set; }
    }
}
