// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_OTROSESTResult
    {
        public decimal IdEs { get; set; }
        public string dir_est { get; set; }
        public string tel_est { get; set; }
        public string codciudad_est { get; set; }
        public string ciudad { get; set; }
        public string Barrio { get; set; }
        public string codbarrio_est { get; set; }
        public string codpais_est { get; set; }
        public string pais { get; set; }
        public string cont_est { get; set; }
        public string email_est { get; set; }
        public string codigo_est { get; set; }
        public string CodPostal { get; set; }
        public string zonas_est { get; set; }
    }
}
