// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ProveeResult
    {
        public string pronit { get; set; }
        public string pronom { get; set; }
        public string tipdocu { get; set; }
        public string digVer { get; set; }
        public string prodir { get; set; }
        public string protel { get; set; }
        public string promail { get; set; }
        public string proprinom { get; set; }
        public string prosegnom { get; set; }
        public string proPriApe { get; set; }
        public string proSegApe { get; set; }
        public string proCuen { get; set; }
        public string proban { get; set; }
        public int proPersona { get; set; }
        public string proPais { get; set; }
        public string proCodCiud { get; set; }
        public string proFax { get; set; }
        public string proconta2 { get; set; }
        public string proced { get; set; }
        public string procargo { get; set; }
        public string proreplegal { get; set; }
        public string proCel { get; set; }
        public int protipcuen { get; set; }
        public decimal proauto { get; set; }
        public decimal proica { get; set; }
        public decimal proautoica { get; set; }
        public string prores2 { get; set; }
        public DateTime profecres2 { get; set; }
        public decimal Rinicial { get; set; }
        public string protipoprovee { get; set; }
        public string procondiciones { get; set; }
        public string procodactividad { get; set; }
        public int prosis { get; set; }
        public string proent { get; set; }
        public string procual { get; set; }
        public int proproc { get; set; }
        public int proesta { get; set; }
        public string prociudades { get; set; }
        public int proase { get; set; }
        public string proasesores { get; set; }
        public int proflex { get; set; }
        public int proCla { get; set; }
        public int procer { get; set; }
        public string DigV { get; set; }
        public int activc { get; set; }
        public string RUt { get; set; }
        public DateTime fechav { get; set; }
        public string Nummatri { get; set; }
        public DateTime InscrR { get; set; }
        public int RUp { get; set; }
        public int certie { get; set; }
        public int timeEnv { get; set; }
        public int garanp { get; set; }
        public int bienser { get; set; }
        public decimal proregi { get; set; }
        public string proconta { get; set; }
        public decimal Rfinal { get; set; }
        public int Generaf { get; set; }
        public string Reteiva { get; set; }
        public string Reteica { get; set; }
        public string Retefuen { get; set; }
        public int plazo { get; set; }
        public int estado { get; set; }
        public decimal proiva { get; set; }
        public decimal progran { get; set; }
        public int prodeclarar { get; set; }
        public string TipoTer { get; set; }
        public string proOblFac { get; set; }
        public string etiqueta { get; set; }
    }
}
