// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PrestAutorResult
    {
        public string numsoli { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string Fecha { get; set; }
        public decimal valors { get; set; }
        public int numcuotas { get; set; }
        public string concepto { get; set; }
        public string egreso { get; set; }
        public string asociado { get; set; }
        public string NombConcepto { get; set; }
        public decimal? ValCon { get; set; }
        public decimal? IntCon { get; set; }
        public string PucCon { get; set; }
        public decimal cuotamen { get; set; }
        public string glnum { get; set; }
        public string Responsable { get; set; }
        public decimal VlrCuotaExtra { get; set; }
        public string PagoInicial { get; set; }
        public int Autorizado { get; set; }
        public decimal VlrPapel { get; set; }
        public string Codeudor1 { get; set; }
        public string Codeudor2 { get; set; }
        public string Estado { get; set; }
        public string SolFuente { get; set; }
        public string DOCAUTO { get; set; }
        public DateTime FechaAuto { get; set; }
        public string NomEmp { get; set; }
        public string cconom { get; set; }
        public string CiudadCedula { get; set; }
        public string CuentaBan { get; set; }
        public DateTime FechaIng { get; set; }
        public string TipDoctAsoc { get; set; }
        public string TipCuentaAsoc { get; set; }
        public string CodBanco { get; set; }
        public string TipoTransaccion { get; set; }
        public string CodCiudad { get; set; }
        public int TipoCliente { get; set; }
    }
}
