// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PRINCPROVResult
    {
        public string Empresa { get; set; }
        public string Sector { get; set; }
        public string Productos { get; set; }
        public string Teléfono { get; set; }
        public string Confirmación { get; set; }
    }
}
