// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PROYEC_RECAUDOResult
    {
        public string Nombres { get; set; }
        public DateTime? fechaPago { get; set; }
        public decimal? Valor1 { get; set; }
        public string Estado { get; set; }
    }
}
