// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PlantillaEmailResult
    {
        public string nombre { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public string para { get; set; }
    }
}
