// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PresupuestoCabecera_DEPENDENCIAResult
    {
        public string PreCabCod { get; set; }
        public string cconom { get; set; }
        public decimal PreCab001 { get; set; }
        public decimal Mes1 { get; set; }
        public decimal Mes2 { get; set; }
        public decimal Mes3 { get; set; }
        public decimal Mes4 { get; set; }
        public decimal Mes5 { get; set; }
        public decimal Mes6 { get; set; }
        public decimal Mes7 { get; set; }
        public decimal Mes8 { get; set; }
        public decimal Mes9 { get; set; }
        public decimal Mes10 { get; set; }
        public decimal Mes11 { get; set; }
        public decimal Mes12 { get; set; }
        public int Periodo { get; set; }
    }
}
