// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PresupuestoGenCotRentabilidadResult
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal Cantidad { get; set; }
        [Column("Unidad de medida")]
        public string Unidaddemedida { get; set; }
        public decimal Costo { get; set; }
        public decimal Rentabilidad { get; set; }
        public decimal Precio { get; set; }
        public int Escala1 { get; set; }
        public int Escala2 { get; set; }
        public int Escala3 { get; set; }
        public int EScala4 { get; set; }
        public int IdITem { get; set; }
    }
}
