// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PucTipoDiferidoResult
    {
        public string DifPuc { get; set; }
        public string DifNom { get; set; }
        public string DifDebe { get; set; }
        public string DifHaber { get; set; }
    }
}
