// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PermisosResult
    {
        public bool? Adicionar { get; set; }
        public bool? Editar { get; set; }
        public bool? Eliminar { get; set; }
        public bool? Imprimir { get; set; }
        public bool? Calcular { get; set; }
    }
}
