// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_PrioridadesResult
    {
        public string Codigo { get; set; }
        public string Nmbre { get; set; }
        public decimal Color { get; set; }
    }
}
