// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_REGEMPResult
    {
        public string NombreCargo { get; set; }
        public string CentroCosto { get; set; }
        public string CodSueldo { get; set; }
        public string CodPrimas { get; set; }
        public string CodVacaciones { get; set; }
        public string CodIncapacidad { get; set; }
        public string CodCesantias { get; set; }
        public string CodIntCesantias { get; set; }
        public string CodSubsidioTransporte { get; set; }
        public string CodDomingosFeriados { get; set; }
        public string CodRecargoNocturno { get; set; }
        public string CodHEOD { get; set; }
        public string CodHEON { get; set; }
        public string CodHEFD { get; set; }
        public string CodHEFN { get; set; }
        public string CodDFN { get; set; }
        public string CodComisiones { get; set; }
        public string CodBonificaciones { get; set; }
        public string CodVivienda { get; set; }
        public string AporteSaludGE { get; set; }
        public decimal PorAporteSaludGE { get; set; }
        public string AporteSaludAdGE { get; set; }
        public decimal PorAporteSaludAdGE { get; set; }
        public string AportePensionGE { get; set; }
        public decimal PorAportePensionGE { get; set; }
        public string AportePensionAdGE { get; set; }
        public decimal PorAportePensionAdGE { get; set; }
        public string AporteSaludEmp { get; set; }
        public decimal PorAporteSaludEmp { get; set; }
        public string AporteSaludAdEmp { get; set; }
        public decimal PorAporteSaludAdEmp { get; set; }
        public string AportePensionEmp { get; set; }
        public decimal PorAportePensionEmp { get; set; }
        public string AportePensionAdEmp { get; set; }
        public decimal PorAportePensionAdEmp { get; set; }
        public string FSP { get; set; }
        public decimal PorFSP { get; set; }
        public string CodCCF { get; set; }
        public decimal PorcCCF { get; set; }
        public string GastoCCF { get; set; }
        public string CodARP { get; set; }
        public decimal PorcARP { get; set; }
        public string GastoARP { get; set; }
        public string CodICBF { get; set; }
        public decimal PorcICBF { get; set; }
        public string GastoICBF { get; set; }
        public string CodSENA { get; set; }
        public decimal PorcSENA { get; set; }
        public string GastoSENA { get; set; }
        public string CodPrimaConvencional { get; set; }
        public string CodPrimaVacacional { get; set; }
        public string CargoCodRet { get; set; }
        public string CargoCesantias { get; set; }
        public string CargoPensiones { get; set; }
        public string CargoEps { get; set; }
        public decimal Cargosuelbas { get; set; }
        public decimal SubTransporte { get; set; }
        public int CargoTurnos { get; set; }
    }
}
