// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ReportesOTResult
    {
        public long? Numero { get; set; }
        public string OrdNro { get; set; }
        public DateTime FechaCierre { get; set; }
        public DateTime Fecha { get; set; }
        public string NombreCliente { get; set; }
        public decimal Valor { get; set; }
        public string Estado { get; set; }
    }
}
