// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_Relacion_Formatos_ChequeoResult
    {
        public int Id { get; set; }
        public int IdDetalleFormato { get; set; }
        public string CodigoPerfil { get; set; }
        public string Observacion { get; set; }
        public string Archivo { get; set; }
        public DateTime Fecha { get; set; }
        public DateTime FechaVence { get; set; }
        public DateTime Fecha_Save { get; set; }
        public string User_Save { get; set; }
        public string User_Modify { get; set; }
        public DateTime Fecha_Modify { get; set; }
        public int IdRecordatorio { get; set; }
    }
}
