// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_RptCumpleañosResult
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Mes { get; set; }
        public int? Dia { get; set; }
        public int? NumMes { get; set; }
    }
}
