// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_REFERResult
    {
        public string banco2 { get; set; }
        public string nro { get; set; }
        public string tipo { get; set; }
        public string banco { get; set; }
    }
}
