// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_RecordatorioDestResult
    {
        public bool? Sel { get; set; }
        public string Empcod { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
    }
}
