// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_RptHojaVidaResult
    {
        public int? CodActivo { get; set; }
        public string mejora { get; set; }
        public DateTime fecha { get; set; }
        public string sprestado { get; set; }
        public string Responsable { get; set; }
        public string ValorAdd { get; set; }
        public string TiempoAdd { get; set; }
        public string tipo { get; set; }
        public string codigo { get; set; }
        public string area { get; set; }
        public string SolucionAplicada { get; set; }
    }
}
