// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_Reemplazar_ArticulosResult
    {
        public string ArtNom { get; set; }
        public string Dependencia { get; set; }
        public decimal ExistenciaXDepen { get; set; }
        public decimal Costo { get; set; }
    }
}
