// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_RecFacturasResult
    {
        public string TipoRecFactura { get; set; }
        public bool? Estado_tipo { get; set; }
        public string NumFac { get; set; }
        public string Codcli { get; set; }
        public string Nomcli { get; set; }
        public string FechaS { get; set; }
        public string PortadorS { get; set; }
        public string FechaD { get; set; }
        public string PortadorD { get; set; }
        public int Codigo { get; set; }
    }
}
