// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ResolucionResult
    {
        public string NumR { get; set; }
        public string prefi { get; set; }
        public int Tipo { get; set; }
        public DateTime fecha { get; set; }
        public decimal Rangoi { get; set; }
        public decimal Rangof { get; set; }
        public string clasificacion { get; set; }
        public int vigente { get; set; }
        public string Nombre { get; set; }
        public int MesesVigente { get; set; }
        public string leyenda { get; set; }
    }
}
