// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_SelectDetalleCotizacionResult
    {
        public int? indice { get; set; }
        public string CodCotizacion { get; set; }
        public string Codigo { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public decimal Cantidad { get; set; }
        public string Medida { get; set; }
        public decimal Valor { get; set; }
        public decimal Descuento { get; set; }
        public decimal IvaPorce { get; set; }
        public decimal SubTotal { get; set; }
        public decimal VlrDescuento { get; set; }
        public decimal ValorIva { get; set; }
        public decimal Total { get; set; }
        public string Tecnico { get; set; }
        public string Dependencia { get; set; }
        public string Escala { get; set; }
        public int Id { get; set; }
        public string Tipo { get; set; }
        public decimal? movValorDolar { get; set; }
        public decimal Rentabilidad { get; set; }
        public decimal costo { get; set; }
        public string ordinal { get; set; }
        public string codArti { get; set; }
    }
}
