// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_SinconizarContabilizar_DBResult
    {
        public string Clicod { get; set; }
        public string CodConcepto { get; set; }
        public string tranom { get; set; }
        public decimal Valor { get; set; }
        public bool Facturar { get; set; }
        public string Tipo { get; set; }
    }
}
