// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ScorProvResult
    {
        public int Orden { get; set; }
        public string Criterio { get; set; }
        public string TipoProv { get; set; }
        public int Porcentaje { get; set; }
    }
}
