// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_ShowitArticuloResult
    {
        public string Descipcion { get; set; }
        public string Codigo { get; set; }
        public string Referencia { get; set; }
        public string Especificacion { get; set; }
        public decimal Escala1 { get; set; }
        public decimal Escala2 { get; set; }
        public decimal Escala3 { get; set; }
        public decimal Escala4 { get; set; }
        public string Grupo { get; set; }
        public string Linea { get; set; }
        public string Marca { get; set; }
        public decimal? Existencia { get; set; }
        public int StockMinimo { get; set; }
        public decimal Costo { get; set; }
        public string Medida { get; set; }
    }
}
