// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_SueldoEmpResult
    {
        public decimal? empSuelBas { get; set; }
        public int PROMEDIO_HORAS_EXTRA { get; set; }
    }
}
