// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_SelectGetPucResult
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Version { get; set; }
        public string Dian { get; set; }
        public string Clasificacion { get; set; }
        public decimal Ccosto { get; set; }
        public decimal Tercero { get; set; }
        public string Delmrk { get; set; }
        public int glPCGA { get; set; }
        public int glNIIF { get; set; }
        public int glEquivalenteNIIF { get; set; }
        public int glreqCree { get; set; }
        public string glActividadEconomica { get; set; }
        public string glDebeCree { get; set; }
        public string glHaberCree { get; set; }
        public int glreqActivo { get; set; }
        public int glOt { get; set; }
        public int glGastoNoDed { get; set; }
        public string CodNiif { get; set; }
        public string NombreNiif { get; set; }
    }
}
