// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_Swicth_BoardResult
    {
        public int SW_1 { get; set; }
        public int SW_2 { get; set; }
        public int SW_3 { get; set; }
        public int SW_4 { get; set; }
        public int SW_5 { get; set; }
        public int SW_6 { get; set; }
        public int SW_7 { get; set; }
        public int SW_8 { get; set; }
        public int SW_9 { get; set; }
    }
}
