// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TrabajosResult
    {
        public string tracod { get; set; }
        public string tranom { get; set; }
        public decimal travlr { get; set; }
        public decimal trapor { get; set; }
        public string tracon { get; set; }
        public decimal traiva { get; set; }
        public string trades { get; set; }
        public int TraTipo { get; set; }
        public string Tracco { get; set; }
    }
}
