// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TrasladosResult
    {
        public string NroTraslado { get; set; }
        public DateTime Fecha { get; set; }
        public string DepOrigen { get; set; }
        public string DepDestino { get; set; }
        public string CodDepOrigen { get; set; }
        public string CodDepDestino { get; set; }
        public byte Estado { get; set; }
    }
}
