// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TipoAusentismoResult
    {
        public string CodAus { get; set; }
        public string NomAus { get; set; }
        public int TipoAus { get; set; }
        public int remu { get; set; }
        public int Vacaciones { get; set; }
        public int Tipo { get; set; }
    }
}
