// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TrazaColumnasResult
    {
        public int Id { get; set; }
        public int IdTraza { get; set; }
        public int Indice { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Control { get; set; }
        public string Valor { get; set; }
        public bool Notificable { get; set; }
        public bool Criterio { get; set; }
    }
}
