// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TercerosGeneralResult
    {
        public string Tipo_Doc { get; set; }
        public string Nit { get; set; }
        public string Dig_Ver { get; set; }
        public string Tipo_Per { get; set; }
        public string Razon_Social { get; set; }
        public string Pri_Ape { get; set; }
        public string Seg_Ape { get; set; }
        public string Pri_Nom { get; set; }
        public string Seg_Nom { get; set; }
        public string Rep_legal { get; set; }
        public string Ced_Replegal { get; set; }
        public string Contacto { get; set; }
        public string Cargo_Cont { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Fax { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string Cuenta { get; set; }
        public string Tipo_Cuenta { get; set; }
        public string Banco { get; set; }
        public string Regimen { get; set; }
        public string CiudadBanco { get; set; }
    }
}
