// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TrazabilidadOtResult
    {
        public string OT { get; set; }
        public string Item { get; set; }
        public string Tipo { get; set; }
        public string Metodo { get; set; }
        public string Tolerancia { get; set; }
    }
}
