// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TrazabilidadOTNewResult
    {
        public int id { get; set; }
        public int orden { get; set; }
        public string nombre { get; set; }
        public string contacto { get; set; }
        public string usuario { get; set; }
        public string estacion { get; set; }
        public bool titulo { get; set; }
        public bool? archivo { get; set; }
        public bool? ver { get; set; }
        public bool? correoEnv { get; set; }
        public DateTime? fecha { get; set; }
        public string cumple { get; set; }
        public string path { get; set; }
        public string estado { get; set; }
        public string tercero { get; set; }
        public string correo { get; set; }
    }
}
