// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TrazaFilasResult
    {
        public int Id { get; set; }
        public int IdTraza { get; set; }
        public int Indice { get; set; }
        public string Caption { get; set; }
    }
}
