// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TipoActivoResult
    {
        public string tacpuc { get; set; }
        public string tacnom { get; set; }
        public decimal tactiempo { get; set; }
        public decimal tacdepre { get; set; }
        public int tacdepreNIIF { get; set; }
        public string tacgastos { get; set; }
        public string tacdepre_aa { get; set; }
        public string tacproductoPr { get; set; }
        public string pacCostoInd { get; set; }
        public decimal tactiempoNiif { get; set; }
    }
}
