// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_TrazaRiesgosResult
    {
        public string documento { get; set; }
        public int item { get; set; }
        public string descripcion { get; set; }
        public string efecto { get; set; }
        public string medidas { get; set; }
    }
}
