// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_UGPPResult
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
    }
}
