// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_VendedoresResult
    {
        public string ventipdoc { get; set; }
        public string venced { get; set; }
        public int venpersona { get; set; }
        public string vennom { get; set; }
        public string venPriApe { get; set; }
        public string venSegApe { get; set; }
        public string venPrinom { get; set; }
        public string venSegnom { get; set; }
        public string venreplegal { get; set; }
        public string vencedreplegal { get; set; }
        public string vencontacto { get; set; }
        public string vencargocontacto { get; set; }
        public string venmail { get; set; }
        public string ventel { get; set; }
        public string vencel { get; set; }
        public string venfax { get; set; }
        public string vendir { get; set; }
        public string venzona { get; set; }
        public string vencodciudad { get; set; }
        public string vencodpais { get; set; }
        public string vencuenta { get; set; }
        public int ventipocuenta { get; set; }
        public string venbanco { get; set; }
        public string contrasenia { get; set; }
        public string VenPreCre { get; set; }
        public string vencre { get; set; }
        public string venrescre { get; set; }
        public string VenPrePOS { get; set; }
        public string VenPOS { get; set; }
        public string VenResPOS { get; set; }
        public int venRegi { get; set; }
        public int IDresolucionFR { get; set; }
        public int IDresolucionCT { get; set; }
    }
}
