// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PA_VehiculosResult
    {
        public string marca { get; set; }
        public string placa { get; set; }
        public string propiedad { get; set; }
        public string propiedadnom { get; set; }
        public string conductorn { get; set; }
        public string modelo { get; set; }
        public string Motor { get; set; }
        public string tipo { get; set; }
        public string tarope { get; set; }
        public string soat { get; set; }
        public string gases { get; set; }
        public string gas { get; set; }
        public string crtm { get; set; }
        public DateTime vtarope { get; set; }
        public DateTime? vsoat { get; set; }
        public DateTime? vgases { get; set; }
        public DateTime? vgas { get; set; }
        public DateTime vcrtm { get; set; }
        public string Empresacod { get; set; }
        public string rutaImagen { get; set; }
    }
}
