// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PRESTAMO_HERRAMIENTA_CONSULTA1Result
    {
        public string nombre { get; set; }
        public DateTime? fecha { get; set; }
        public string documento { get; set; }
        public string fecha_devolucion { get; set; }
        public int? dias { get; set; }
        public string area { get; set; }
        public string responsable { get; set; }
        public string OT_destino { get; set; }
        public string serial { get; set; }
        public int prestados { get; set; }
        public int hdevueltos { get; set; }
        public int? saldo { get; set; }
        public decimal id { get; set; }
        public string idmovimiento { get; set; }
        public int? codigo { get; set; }
    }
}
