// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PRESTAMO_HERRAMIENTA_IMPRESIONResult
    {
        public string Tipo1 { get; set; }
        public DateTime fecha { get; set; }
        public string documento { get; set; }
        public string area { get; set; }
        public string retorno_sugerido { get; set; }
        public string responsable { get; set; }
        public string ot { get; set; }
        public string estado1 { get; set; }
        public string estado { get; set; }
        public int tipo { get; set; }
        public string empcod { get; set; }
        public string nombre { get; set; }
        public string unidad { get; set; }
        public string codigo { get; set; }
        public string serial { get; set; }
        public int? cantidad { get; set; }
        public string referencia { get; set; }
    }
}
