// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Print_Orden_CompraResult
    {
        public string numOrden { get; set; }
        public string numRequisicion { get; set; }
        public decimal vlrTotal { get; set; }
        public string MontoEscrito { get; set; }
        public decimal? descuento { get; set; }
        public decimal? ivaArticulo { get; set; }
        public string numFactura { get; set; }
        public string nitProveedor { get; set; }
        public string cabezeraOT { get; set; }
        public string codArti { get; set; }
        public decimal? cantArti { get; set; }
        public int ReqOrdenAutorizada { get; set; }
        public string nomProv { get; set; }
        public string dirProv { get; set; }
        public string mailProv { get; set; }
        public string ciudadProv { get; set; }
        public string telProv { get; set; }
        public string Observacion { get; set; }
        public string cabezeraOriginador { get; set; }
        public string nomOriginador { get; set; }
        public string cabezeraCCO { get; set; }
        public string cabezeraDependencia { get; set; }
        public string nombreDependencia { get; set; }
        public string nombreCCO { get; set; }
        public string COMITE { get; set; }
        public string moneda { get; set; }
        public string tiempoEntrega { get; set; }
        public string formaPago { get; set; }
        public decimal? ivaTotalValor { get; set; }
        public string medida { get; set; }
        public string descripcionArti { get; set; }
        public string referenciaArti { get; set; }
        public decimal? vlrUnitario { get; set; }
        public decimal? descuentoTotal { get; set; }
        public DateTime fecha { get; set; }
        public decimal? valorArticulo { get; set; }
        public decimal? subTotal { get; set; }
        public string userAut { get; set; }
        public string usuario { get; set; }
        public string firmaUserAut { get; set; }
        public string Destino { get; set; }
    }
}
