// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PRO_COnsulta_AnticiposResult
    {
        public decimal? SaldoAnticipo { get; set; }
        public string CuentaAnticipo { get; set; }
    }
}
