// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Inscripcion_MatResult
    {
        public string Cuenta { get; set; }
        public string Serapador1 { get; set; }
        public string Tipo_Cuenta { get; set; }
        public string Serapador2 { get; set; }
        public string Tercero { get; set; }
        public string Serapador3 { get; set; }
        public string Entidad { get; set; }
        public string Serapador4 { get; set; }
        public string Identificacion { get; set; }
        public string Serapador5 { get; set; }
        public string TipoDoc { get; set; }
        public string Serapador6 { get; set; }
        public string Validacion { get; set; }
        public string Serapador7 { get; set; }
        public string Direccion { get; set; }
        public string Serapador8 { get; set; }
        public string Ciudad { get; set; }
        public string Serapador9 { get; set; }
        public string Email { get; set; }
        public string Serapador10 { get; set; }
        public string Telefono { get; set; }
        public string Serapador11 { get; set; }
        public string Fax { get; set; }
        public string Serapador12 { get; set; }
        public string Tope { get; set; }
    }
}
