// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_Articulos_DesproduccionResult
    {
        public string arcod { get; set; }
        public string arespe { get; set; }
        public decimal Existencia { get; set; }
        public string medida { get; set; }
        public int SEL { get; set; }
        public decimal topeMaximo { get; set; }
        public decimal costo { get; set; }
    }
}
