// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Requisiciones_ComprarResult
    {
        public string ReqNro { get; set; }
        public string ReqEle { get; set; }
        public string arespe { get; set; }
        public string ReqMed { get; set; }
        public decimal ReqSol { get; set; }
        public decimal arcosto { get; set; }
        public string depnom { get; set; }
        public int sel { get; set; }
        public int ReqEst { get; set; }
        public string ReqDep { get; set; }
        public decimal ariva { get; set; }
        public int descuento { get; set; }
        public decimal ArVenta { get; set; }
        public decimal ArDisco { get; set; }
        public decimal ArEven { get; set; }
        public decimal ArPrecio { get; set; }
        public int consumo { get; set; }
        public decimal ArMinimo { get; set; }
        public decimal id_unico { get; set; }
        public string linNom { get; set; }
        public string marNom { get; set; }
    }
}
