// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Imprimir_NotaResult
    {
        public string MasCod { get; set; }
        public string MasDoc { get; set; }
        public DateTime? MasFec { get; set; }
        public string MasFte { get; set; }
        public string MasDet { get; set; }
        public string MasCco { get; set; }
        public decimal? MasDeb { get; set; }
        public decimal? MasHbr { get; set; }
        public string Tercero { get; set; }
        public string cconom { get; set; }
        public string Fuente { get; set; }
        public string Cuenta { get; set; }
        public string nomempresa { get; set; }
        public string nitempresa { get; set; }
        public string conciudad { get; set; }
    }
}
