// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_vacaciones_pendientesResult
    {
        public string empnom { get; set; }
        public string empced { get; set; }
        public decimal? EmpSuelBas { get; set; }
        public DateTime? inicio { get; set; }
        public DateTime? final { get; set; }
        public int DayCom { get; set; }
        public int DayDis { get; set; }
        public DateTime? DInicio { get; set; }
        public DateTime? DFinal { get; set; }
        public DateTime? Freintegro { get; set; }
        public int ultimo_sueldo { get; set; }
        public int otras_bases { get; set; }
        public string EmpCod { get; set; }
        public string ff { get; set; }
        public string cargo { get; set; }
        public string tipo_contrato { get; set; }
        public int NovIBCAnterior { get; set; }
    }
}
