// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_conciliacionResult
    {
        public string codigo { get; set; }
        public string dependencia { get; set; }
        public DateTime fecha { get; set; }
        public string usuario { get; set; }
        public string estacion { get; set; }
        public DateTime fechaServer { get; set; }
    }
}
