// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Auditora_DoocumentosResult
    {
        public string Masdoc { get; set; }
        public string Fecha { get; set; }
        public string MasFte { get; set; }
        public string FteNom { get; set; }
        public decimal? MasDeb { get; set; }
        public decimal? MasHbr { get; set; }
        public decimal? valor { get; set; }
        public DateTime? MasFec { get; set; }
    }
}
