// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Cierre_Venta_IMPRIMIRResult
    {
        public string Tipo { get; set; }
        public decimal? Valor { get; set; }
        public DateTime? FechaServer { get; set; }
        public string CodTercero { get; set; }
    }
}
