// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Generar_OrdenResult
    {
        public string Proveedor { get; set; }
        public DateTime? Fecha_Solicitud { get; set; }
        public string Tipo { get; set; }
        public string ID { get; set; }
        public string Dependencia { get; set; }
        public string Centro_Costo { get; set; }
        public string Detalle { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? Valor_Unitario { get; set; }
        public decimal? Valor_Total { get; set; }
        public string Estado { get; set; }
    }
}
