// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Print_Orden_entrega_compraResult
    {
        public string NOMEMP { get; set; }
        public string NITEMP { get; set; }
        public string DIREMP { get; set; }
        public string TELEMP { get; set; }
        public string CIUEMP { get; set; }
        public string nomcli { get; set; }
        public string codcli { get; set; }
        public string dircli { get; set; }
        public string nomZona { get; set; }
        public string cliciud { get; set; }
        public string cVendedor { get; set; }
        public DateTime fecha { get; set; }
        public DateTime vencimiento { get; set; }
        public string numeroPedido { get; set; }
        public string codArt { get; set; }
        public string desart { get; set; }
        public string Medart { get; set; }
        public decimal canart { get; set; }
        public string lotnom { get; set; }
        public decimal vunart { get; set; }
        public string Referencia { get; set; }
    }
}
