// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Listado_CXPResult
    {
        public string pronit { get; set; }
        public string pronit1 { get; set; }
        public string pronom { get; set; }
        public string nrofac { get; set; }
        public string detalle { get; set; }
        public decimal? saldo { get; set; }
        public DateTime? vencimiento { get; set; }
        public decimal valor { get; set; }
        public DateTime? fecfac { get; set; }
        public decimal pagval { get; set; }
        public int estado { get; set; }
    }
}
