// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Cargar_IncapacidadResult
    {
        public int id_Unico { get; set; }
        public decimal Id_Prorroga { get; set; }
        public string CodEmp { get; set; }
        public string CodAusen { get; set; }
        public DateTime Fecha1 { get; set; }
        public DateTime Fecha2 { get; set; }
        public int? Dias { get; set; }
        public int? DiasAnt { get; set; }
    }
}
