// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Cotizaciones_IngecoolResult
    {
        public string cotnum { get; set; }
        public int? año { get; set; }
        public string mes { get; set; }
        public DateTime? FechaHora { get; set; }
        public string cliente { get; set; }
        public string cotdet { get; set; }
        public decimal? cotcan { get; set; }
        public int? cotiva { get; set; }
        public decimal? cottot { get; set; }
        public string estado { get; set; }
        public int CotTip { get; set; }
        public string cotcondi { get; set; }
        public string vendedor { get; set; }
        public string cotvali { get; set; }
        public string cotforpa { get; set; }
        public string cotgar { get; set; }
        public string cotna { get; set; }
        public decimal cotflete { get; set; }
        public decimal cotdcto { get; set; }
        public decimal cotrete { get; set; }
        public decimal cotTipoCambio { get; set; }
        public string cotCalifica { get; set; }
        public DateTime cotfecestado { get; set; }
        public string cotfactura { get; set; }
        public string cotFecFactura { get; set; }
        public string cotescala { get; set; }
        public string cotusuario { get; set; }
        public string cotEstacion { get; set; }
        public string cotOT { get; set; }
        public string cotFechaOT { get; set; }
        public string Solicitante { get; set; }
        public decimal Descuento { get; set; }
        public int DesdeOt { get; set; }
        public string escala { get; set; }
    }
}
