// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Estado_CostoResult
    {
        public string glcod { get; set; }
        public string glnum { get; set; }
        public string Sub_Centro_Costo { get; set; }
        public string Centro_Costo { get; set; }
        public decimal? glSaldoIni { get; set; }
        public decimal? Debe { get; set; }
        public decimal? Haber { get; set; }
        public decimal? SaldoFin { get; set; }
    }
}
