// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_ImputacionBorrarResult
    {
        public string mascod { get; set; }
        public string glnum { get; set; }
        public decimal? masdeb { get; set; }
        public decimal? mashbr { get; set; }
    }
}
