// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Requicisiones_CompraResult
    {
        public string REQNRO { get; set; }
        public string fecha { get; set; }
        public string ReqFecEnt { get; set; }
        public string depnom { get; set; }
        public string empNom { get; set; }
        public string cconom { get; set; }
        public string dprnom { get; set; }
        public string Estado { get; set; }
        public string REQDEP { get; set; }
        public string REQTYP { get; set; }
        public int REQEST { get; set; }
        public decimal Req_Id_Unico { get; set; }
        public int ReqAutorizado { get; set; }
        public string OTnumero { get; set; }
        public string ReqEstado { get; set; }
        public decimal id_unico { get; set; }
        public DateTime fechaCreacion { get; set; }
        public string usuario { get; set; }
        public string estacion { get; set; }
        public string REQDES { get; set; }
    }
}
