// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Generar_Novedades_NominaResult
    {
        public string CodConcepto { get; set; }
        public string ConNom { get; set; }
        public int TipoCobro { get; set; }
        public decimal Valor { get; set; }
        public string ConAux { get; set; }
        public string ConCre { get; set; }
        public int ConSal { get; set; }
        public int ConPen { get; set; }
        public int ConFsp { get; set; }
        public int ConRet { get; set; }
        public decimal conPor { get; set; }
        public int TipoConcepto { get; set; }
        public decimal Ibc { get; set; }
        public int convlrdia { get; set; }
        public decimal SaldoAcu { get; set; }
        public DateTime FecIni { get; set; }
        public DateTime Fecfin { get; set; }
        public decimal Monto { get; set; }
        public int Forma { get; set; }
        public string CodTercero { get; set; }
        public int id { get; set; }
        public int estado { get; set; }
        public string ccocod { get; set; }
        public decimal diashc { get; set; }
        public string Centros_FIjos { get; set; }
    }
}
