// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Preoper_NetResult
    {
        public int Id_pti { get; set; }
        public string Operacion { get; set; }
        public DateTime fecha { get; set; }
        public string equipo { get; set; }
        public string nomEquipo { get; set; }
        public string conductor { get; set; }
        public string clinom { get; set; }
        public string operativo { get; set; }
    }
}
