// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Consulta_PorResult
    {
        public string MasCod { get; set; }
        public string FteNom { get; set; }
        public string MasDoc { get; set; }
        public DateTime? MasFec { get; set; }
        public string MasDet { get; set; }
        public decimal MasDeb { get; set; }
        public decimal MasHbr { get; set; }
        public string glnum { get; set; }
        public string Nit_Tercero { get; set; }
        public string TerNom { get; set; }
        public string cconom { get; set; }
        public string masFte { get; set; }
        public string masCco { get; set; }
        public DateTime? MasUpd { get; set; }
        public string masway { get; set; }
        public string masot { get; set; }
        public string nomprogru { get; set; }
        public decimal MasBaseRete { get; set; }
        public decimal? MasPorRete { get; set; }
        public string ciunom { get; set; }
        public string NomPais { get; set; }
        public string terdir { get; set; }
        public string nomdpto { get; set; }
        public string DigVer { get; set; }
        public string Tertel { get; set; }
        public string Tercel { get; set; }
        public string Termail { get; set; }
        public string ActividadEco { get; set; }
        public string UserAdd { get; set; }
        public string EstAdd { get; set; }
    }
}
