// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Venta_DetalleResult
    {
        public string CodArti { get; set; }
        public string DesArti { get; set; }
        public string Referencia { get; set; }
        public string Medida { get; set; }
        public decimal Cantidad { get; set; }
        public decimal? vUni { get; set; }
        public decimal ariva { get; set; }
        public decimal nDesc { get; set; }
        public decimal cantDev { get; set; }
        public string NOMdependencia { get; set; }
        public string Linea { get; set; }
        public string Grupo { get; set; }
        public string Marca { get; set; }
        public string TipoMov { get; set; }
        public string Cotizacion { get; set; }
        public string fCoti { get; set; }
        public string Remision { get; set; }
        public string fRemi { get; set; }
        public string Orden { get; set; }
        public string fOrden { get; set; }
        public string Tecnico { get; set; }
        public string tecCod { get; set; }
        public string nroFac { get; set; }
        public string TipoDoc { get; set; }
        public string depcod { get; set; }
        public decimal ComEqu { get; set; }
        public decimal comcos { get; set; }
        public decimal id_unico { get; set; }
        public decimal comvlrIva { get; set; }
        public int comVlrImp { get; set; }
        public int comlote { get; set; }
        public string ctaInv { get; set; }
        public string ctaCos { get; set; }
        public string CtaIng { get; set; }
        public string contrato { get; set; }
        public decimal? vUniIva { get; set; }
        public int IvaInc { get; set; }
        public string DocumentoNew { get; set; }
        public decimal CantidadDev { get; set; }
        public int Sel { get; set; }
        public string lotnom { get; set; }
        public decimal DevIvadet { get; set; }
        public decimal ImpArt { get; set; }
    }
}
