// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_gestion_swResult
    {
        public int SW_COD { get; set; }
        public string SW_Frm { get; set; }
        public string proposito { get; set; }
        public bool? SW_1 { get; set; }
        public bool? SW_2 { get; set; }
        public bool? SW_3 { get; set; }
        public bool? SW_4 { get; set; }
        public bool? SW_5 { get; set; }
        public bool? SW_6 { get; set; }
        public bool? SW_7 { get; set; }
        public bool? SW_8 { get; set; }
        public bool? SW_9 { get; set; }
    }
}
