// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_AutoreteNetResult
    {
        public int AutoCree { get; set; }
        public string CtaAutoCree { get; set; }
        public decimal PorAutoCree { get; set; }
        public string CtaDbAutoCree { get; set; }
        public string NomCtaDbAutoCree { get; set; }
        public string NomCtaCrAutoCree { get; set; }
    }
}
