// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_pqrTratamientoResult
    {
        public string codigo { get; set; }
        public string actividad { get; set; }
        public string responsable { get; set; }
        public DateTime fecha { get; set; }
        public string responsableCodigo { get; set; }
    }
}
