// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class PROC_SERVICIOSResult
    {
        public string tracod { get; set; }
        public string tranom { get; set; }
        public string tramed { get; set; }
        public decimal costo { get; set; }
        public decimal traiva { get; set; }
        public decimal traImpoconsumo { get; set; }
        public decimal escala1 { get; set; }
        public decimal precio1 { get; set; }
        public decimal escala2 { get; set; }
        public decimal precio2 { get; set; }
        public decimal escala3 { get; set; }
        public decimal precio3 { get; set; }
        public decimal escala4 { get; set; }
        public decimal precio4 { get; set; }
        public string linea { get; set; }
        public string grupo { get; set; }
        public string tipo_servicio { get; set; }
        public string centro_costo { get; set; }
        public decimal tiempoEstimado { get; set; }
        public int proxRevision { get; set; }
    }
}
