// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_InvLineasResult
    {
        public string nombre { get; set; }
        public decimal utilidad { get; set; }
        public string invgravado { get; set; }
        public string invexento { get; set; }
        public string invexcluido { get; set; }
        public string cosgravado { get; set; }
        public string cosexento { get; set; }
        public string cosexcluido { get; set; }
        public string inggravado { get; set; }
        public string ingexento { get; set; }
        public string ingexcluido { get; set; }
        public string LinCtaReteFte { get; set; }
        public string LinCtaReteIca { get; set; }
        public string LinCtaReteIVA { get; set; }
        public string LinCtaReteFteComun { get; set; }
        public int linDotacion { get; set; }
        public string LinCtaAntReteFteIVA { get; set; }
        public string LinCtaAntReteFte { get; set; }
        public string LinCtaAntReteICA { get; set; }
        public string LinCtaAntReteIVA { get; set; }
        public string LinCtaAntReteGarantia { get; set; }
    }
}
