// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Auditoria_InventarioResult
    {
        public string CODARTICULO { get; set; }
        public string ARTICULO { get; set; }
        public string CODDEPENDENCIA { get; set; }
        public string DEPENDENCIA { get; set; }
        public decimal EXISTENCIA { get; set; }
        public decimal CANTIDAD_LOTE { get; set; }
        public decimal? Diferencia { get; set; }
        public string LINEA { get; set; }
        public string GRUPO { get; set; }
    }
}
