// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Inventario_MedidaResult
    {
        public string Producto_Principal { get; set; }
        public string Codigo { get; set; }
        public string Nom_Articulo { get; set; }
        public decimal? Total { get; set; }
        public decimal Kilo { get; set; }
        public decimal Unidad { get; set; }
        public decimal Par { get; set; }
    }
}
