// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_CalifiCartetaResult
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal interesImplicito { get; set; }
        public int dias { get; set; }
        public string debito { get; set; }
        public string credito { get; set; }
    }
}
