// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Imprimir_RCResult
    {
        public DateTime? BKFEC { get; set; }
        public string bkdoc { get; set; }
        public string conciudad { get; set; }
        public string TERNOM { get; set; }
        public string glnum { get; set; }
        public string BKCOD { get; set; }
        public string bkdet { get; set; }
        public string bkchk { get; set; }
        public double? bkdeb { get; set; }
        public double? bkhbr { get; set; }
        public string BKBCO { get; set; }
        public DateTime BKFECHACH { get; set; }
        public string Titulo1 { get; set; }
        public string Nit { get; set; }
        public string BKCLS { get; set; }
        public string DocumentoNew { get; set; }
    }
}
