// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_GET_DATA_articulosResult
    {
        public string arespecificacion { get; set; }
        public string linnom { get; set; }
        public string desnom { get; set; }
        public string marnom { get; set; }
        public decimal stockMin { get; set; }
        public string arfoto { get; set; }
    }
}
