// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Facturar_CompraResult
    {
        public decimal? reqpmp { get; set; }
        public decimal reqcan { get; set; }
        public decimal? reqvlr { get; set; }
        public decimal? reqdes { get; set; }
        public decimal? reqiva { get; set; }
        public decimal? VlrImpoconsumo { get; set; }
        public decimal? reqTotal { get; set; }
        public decimal? PorImpoconsumo { get; set; }
        public int descuento { get; set; }
        public string deppuc { get; set; }
        public string reqele { get; set; }
        public decimal Tarifa { get; set; }
        public string depnom { get; set; }
        public string arespe { get; set; }
        public string reqdep { get; set; }
        public string arcod { get; set; }
        public int? artipoar { get; set; }
        public string reqFac { get; set; }
        public string reqCcosto { get; set; }
        public string reqord { get; set; }
        public decimal? reqpre { get; set; }
        public int ReqTipIva { get; set; }
        public string numeroOT { get; set; }
    }
}
