// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Tributario2Result
    {
        public string RetPuc { get; set; }
        public string CodPro { get; set; }
        public string TerNom { get; set; }
        public string RetNom { get; set; }
        public decimal? RetPor { get; set; }
        public string TerNit { get; set; }
        public string TerCiu { get; set; }
        public decimal? Base { get; set; }
        public decimal? SumaHaber { get; set; }
        public string Terdir { get; set; }
        public string termail { get; set; }
    }
}
