// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_ConsulContabilidad_NetResult
    {
        public string DOCUMENTO { get; set; }
        public DateTime? FECHA { get; set; }
        public string CONCEPTO { get; set; }
        public decimal? VALOR { get; set; }
    }
}
