// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_SancioCuestionarioResult
    {
        public string codigoEmpleado { get; set; }
        public string codigoFalta { get; set; }
        public DateTime fechaevento { get; set; }
        public DateTime horafalta { get; set; }
        public string codigoTestigo { get; set; }
        public DateTime horaFinDescargo { get; set; }
        public DateTime FecCitacionDescargo { get; set; }
        public DateTime horaInicioDescargo { get; set; }
    }
}
