// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Imprimir_EtiquetaResult
    {
        public string Descripcion { get; set; }
        public string numero { get; set; }
        public string Cod_Articulo { get; set; }
        public string Nom_Lote { get; set; }
        public DateTime Fecha { get; set; }
        public string Dependencia { get; set; }
        public decimal Cant_Transformacion { get; set; }
        public decimal? Exi_Actual { get; set; }
        public string MedArtDes { get; set; }
    }
}
