// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_SaldoInicialesNetResult
    {
        public string bkchk { get; set; }
        public DateTime bkfec { get; set; }
        public string bkDet { get; set; }
        public string bknit { get; set; }
        public double bkdeb { get; set; }
        public string idTercero { get; set; }
        public int ID { get; set; }
    }
}
