// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_GriArticulosResult
    {
        public bool? Descontinuar { get; set; }
        public string Codigo { get; set; }
        public string arespe { get; set; }
        public string arref { get; set; }
        public string arEspecificacion { get; set; }
        public decimal? cantidadTotal { get; set; }
        public decimal arcosto { get; set; }
        public decimal arventa { get; set; }
        public decimal DescMax1 { get; set; }
        public decimal ardisco { get; set; }
        public decimal DescMax2 { get; set; }
        public decimal areven { get; set; }
        public decimal DescMax3 { get; set; }
        public decimal arPrecio { get; set; }
        public decimal DescMax4 { get; set; }
        public decimal ariva { get; set; }
        public decimal arMinimo { get; set; }
        public int arlote { get; set; }
        public decimal ardosificacion { get; set; }
        public DateTime? FechaUltCompra { get; set; }
        public string proveedor { get; set; }
        public string arbarras { get; set; }
        public string Modalidad { get; set; }
        public decimal CostoUltCompra { get; set; }
        public string Usuario { get; set; }
        public string Estacion { get; set; }
        public DateTime Fecha_Creacion { get; set; }
    }
}
