// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_Ventas_Maroel_DETALLEResult
    {
        public string codigo { get; set; }
        public string referencia { get; set; }
        public string descripcion { get; set; }
        public decimal cantidad { get; set; }
        public string medida { get; set; }
        public decimal precio { get; set; }
        public decimal? subtotal { get; set; }
        public decimal iva { get; set; }
        public string dependencia { get; set; }
        public string escala { get; set; }
        public string MovDep { get; set; }
        public string MovEsc { get; set; }
        public int id_unico { get; set; }
        public string MovCtz { get; set; }
        public decimal? arMinimo { get; set; }
        public string movtip { get; set; }
        public string armed { get; set; }
        public decimal movcos { get; set; }
        public decimal ArDescuento { get; set; }
        public string bodegaGL { get; set; }
        public string recibeGL { get; set; }
        public string entregaGL { get; set; }
    }
}
