// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Armar_Doc_ComprasResult
    {
        public string Cuenta { get; set; }
        public string NomCuenta { get; set; }
        public decimal? VlrDeb { get; set; }
        public decimal? VlrCre { get; set; }
        public decimal? Base { get; set; }
        public decimal? Porcentaje { get; set; }
        public string TipoImpuesto { get; set; }
        public string Factura { get; set; }
        public DateTime? Fecha { get; set; }
        public string CodProveedor { get; set; }
        public string SubCCosto { get; set; }
        public string NomSubCentro { get; set; }
        public string CodTercero { get; set; }
        public string NomTercero { get; set; }
        public string OT { get; set; }
        public string Tipo { get; set; }
        public int? Orden { get; set; }
    }
}
