// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_CtaDispersablesResult
    {
        public string Codigo { get; set; }
        public string CodigoPuc { get; set; }
        public string Nombre { get; set; }
    }
}
