// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Magneticos_CxPResult
    {
        public string TipoDoc { get; set; }
        public string Ident { get; set; }
        public string Razon_Social { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Primer_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Factura { get; set; }
        public DateTime Fecha { get; set; }
        public decimal Vlr_Factura { get; set; }
        public decimal Base { get; set; }
        public string Cuenta { get; set; }
        public decimal? Porc_ReteFte { get; set; }
        public decimal Vlr_ReteFuente { get; set; }
        public decimal Porc_ReteICA { get; set; }
        public decimal Vlr_ReteIca { get; set; }
        public decimal Porc_ReteIVA { get; set; }
        public decimal Vlr_ReteIva { get; set; }
        public decimal Porc_IVA { get; set; }
        public decimal Vlr_Iva { get; set; }
        public string Cod_Ciudad { get; set; }
        public string Cod_Pais { get; set; }
    }
}
