// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Print_PEDIDO_GLResult
    {
        public decimal? id_unico { get; set; }
        public string NOMEMP { get; set; }
        public string NITEMP { get; set; }
        public string DIREMP { get; set; }
        public string TELEMP { get; set; }
        public string NroFac { get; set; }
        public string CIUEMP { get; set; }
        public string TIPODOC { get; set; }
        public string RESOLUCION { get; set; }
        public string CODESCALA { get; set; }
        public DateTime LOTFECVEN { get; set; }
        public string NOMCLI { get; set; }
        public string CODCLI { get; set; }
        public string DIRCLI { get; set; }
        public decimal SUBTOTALCAB { get; set; }
        public DateTime? FECHA { get; set; }
        public decimal IVA { get; set; }
        public decimal FLETE { get; set; }
        public string CLICIUD { get; set; }
        public DateTime? VENCIMIENTO { get; set; }
        public string TELCLI { get; set; }
        public string CVENDEDOR { get; set; }
        public string TPODOC { get; set; }
        public string NRODOC { get; set; }
        public decimal? CANART { get; set; }
        public string MEDART { get; set; }
        public string DESART { get; set; }
        public decimal? VUNART { get; set; }
        public decimal? IVAART { get; set; }
        public decimal? DSUBTOTAL { get; set; }
        public decimal? subGravado { get; set; }
        public string OBSFAC { get; set; }
        public decimal rtiva { get; set; }
        public decimal rtica { get; set; }
        public decimal rtfte { get; set; }
        public decimal rtcree { get; set; }
        public string REFERENCIA { get; set; }
        public string Laboratorio { get; set; }
        public string LotNom { get; set; }
        public string codimp { get; set; }
        public string CDETALLE { get; set; }
        public string Escala { get; set; }
        public string nomZona { get; set; }
        public decimal TOTAL { get; set; }
        public decimal TCAMBIO { get; set; }
        public decimal VLRDESCUENTO { get; set; }
        public string CODART { get; set; }
        public string marca { get; set; }
        public string MOVDEP { get; set; }
        public string linnom { get; set; }
        public decimal Anticipos { get; set; }
        public decimal saldo { get; set; }
        public decimal? nporc { get; set; }
        public decimal? nAUIvalor { get; set; }
        public decimal? nCostoDirecto { get; set; }
        public decimal? nBaseG { get; set; }
        public decimal AntFactura { get; set; }
        public string numeroPedido { get; set; }
        public string TipoFactura { get; set; }
        public string OTNumero { get; set; }
        public decimal Impoconsumo { get; set; }
        public int Cuotas { get; set; }
        public decimal PorInt { get; set; }
        public string direccion { get; set; }
        public string Telefono { get; set; }
        public string imgFoto { get; set; }
    }
}
