// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Informe_Ventas_RelojesResult
    {
        public string NIT { get; set; }
        public string Razon_Social { get; set; }
        public string Fecha { get; set; }
        public string NroFac { get; set; }
        public string detalle { get; set; }
        public int? Cantidad { get; set; }
        public decimal? VlrUni { get; set; }
        public decimal? VlrIVA { get; set; }
        public decimal? VlrImp { get; set; }
        public decimal? VlrTotal { get; set; }
        public string Hora { get; set; }
        public string Forma_Pago { get; set; }
    }
}
