// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Requisiciones_GLAPPResult
    {
        public string oricod { get; set; }
        public string nombre { get; set; }
        public string cargo { get; set; }
    }
}
