// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Consultar_IncapacidadResult
    {
        public int IdAusentismo { get; set; }
        public string TipoLiq { get; set; }
        public int TipoAusentismo { get; set; }
        public string CodEmpleado { get; set; }
        public string Concepto { get; set; }
        public int? Dias { get; set; }
        public decimal? Valor { get; set; }
        public decimal? ValorSeguridad { get; set; }
        public string Cuenta { get; set; }
        public string NomConcepto { get; set; }
        public string CodTercero { get; set; }
    }
}
