// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_recibo_compraResult
    {
        public string sel { get; set; }
        public string ReqFac { get; set; }
        public string reqord { get; set; }
        public int reqInv { get; set; }
        public string pronom { get; set; }
        public DateTime reqfor { get; set; }
        public decimal? subtotal { get; set; }
        public decimal reqiva { get; set; }
        public decimal reqdto { get; set; }
        public string reqcer { get; set; }
        public string reqpro { get; set; }
        public decimal total { get; set; }
        public decimal reqImp { get; set; }
        public string Moneda { get; set; }
        public decimal tipoCambio { get; set; }
        public bool excluido { get; set; }
        public string Nota { get; set; }
        public string NumeroOT { get; set; }
        public decimal? porcentaje_orden { get; set; }
        public decimal? porcentaje_orden2 { get; set; }
        public DateTime fechaServer { get; set; }
        public string userAdd { get; set; }
        public string estacion { get; set; }
        public int? DiasCumpli { get; set; }
        public int ReqOrdConLote { get; set; }
    }
}
