// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Causar_Mercancia_ConsignacionResult
    {
        public string ReqNro { get; set; }
        public DateTime Fecha { get; set; }
        public string ReqEle { get; set; }
        public string Arespe { get; set; }
        public double ReqSol { get; set; }
        public decimal ReqVlr { get; set; }
        public string PRONOM { get; set; }
        public int Sel { get; set; }
        public string Cta_Inv { get; set; }
    }
}
