// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_RptSaldosBancariosResult
    {
        public string delmrk { get; set; }
        public string bancod { get; set; }
        public string bannom { get; set; }
        public decimal bansal { get; set; }
        public string banch { get; set; }
        public int bangr { get; set; }
        public DateTime banfec { get; set; }
        public decimal banini { get; set; }
        public string banrep1 { get; set; }
        public string banrep2 { get; set; }
        public string banpla { get; set; }
        public string BanNro { get; set; }
        public string BanTip { get; set; }
        public string TipoConCepto { get; set; }
        public string nomReporte { get; set; }
        public string nomempresa { get; set; }
        public string nitempresa { get; set; }
    }
}
