// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Lista_CXP_AutomaticoResult
    {
        public string origen { get; set; }
        public string pronom { get; set; }
        public string NumFac { get; set; }
        public DateTime fechaFac { get; set; }
        public string orden { get; set; }
        public decimal valorCXP { get; set; }
        public int SEL { get; set; }
        public string tipoproveedor { get; set; }
        public string CodigoCont { get; set; }
        public string pronit { get; set; }
        public string ProveedorID { get; set; }
        public int tipoFAC { get; set; }
    }
}
