// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_CfgPlanillaResult
    {
        public string proveedor { get; set; }
        public string tipoMovimiento { get; set; }
        public string tipoProveedor { get; set; }
        public string fuenteConfig { get; set; }
        public int controlLectura { get; set; }
    }
}
