// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Anticipos_LEGALIZARResult
    {
        public string pronit1 { get; set; }
        public string pronom { get; set; }
        public decimal? SalAnt { get; set; }
        public int EstAnt { get; set; }
        public string CodAnt { get; set; }
        public string DetAnt { get; set; }
        public string proNit { get; set; }
        public int ValAnt { get; set; }
        public string CodCli { get; set; }
        public string FecAnt { get; set; }
        public string TipAnt { get; set; }
        public int IngInv { get; set; }
        public string CodArt { get; set; }
        public string UsuAnt { get; set; }
        public string UltAnt { get; set; }
    }
}
