// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_planilla_combustible_proveedorResult
    {
        public string pronom { get; set; }
        public int vehiculo { get; set; }
        public string nombre { get; set; }
        public decimal? cantidad { get; set; }
        public decimal? total { get; set; }
        public string codigo { get; set; }
    }
}
