// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Ventas_IngecoolResult
    {
        public DateTime? FECHA { get; set; }
        public string NIT { get; set; }
        public string CLIENTE { get; set; }
        public string FACTURA { get; set; }
        public decimal VENTA_GRAVADA { get; set; }
        public decimal VENTA_AIU { get; set; }
        public decimal IVA { get; set; }
        public decimal RTEFTE { get; set; }
        public decimal RETEICA { get; set; }
        public decimal RETEIVA { get; set; }
        public decimal? RETECREE { get; set; }
    }
}
