// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Cuentas_PagarResult
    {
        public string nrofac { get; set; }
        public string nrocxp { get; set; }
        public int diaven { get; set; }
        public DateTime? fecfac { get; set; }
        public string detalle { get; set; }
        public decimal vlrfac { get; set; }
        public decimal? abonof { get; set; }
        public decimal saldo { get; set; }
        public string protipo { get; set; }
        public string cCosto { get; set; }
        public string codpro { get; set; }
    }
}
