// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_nePermisoCartasResult
    {
        public string Empleado { get; set; }
        public string Jefe { get; set; }
        public DateTime FecCitacionDescargo { get; set; }
        public string falta { get; set; }
    }
}
