// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_remisiones_DETALLADOResult
    {
        public string Remision { get; set; }
        public DateTime Fecha { get; set; }
        public string Cliente { get; set; }
        public string vennom { get; set; }
        public decimal saldo { get; set; }
        public decimal remvlr { get; set; }
        public decimal remsub { get; set; }
        public decimal remiva { get; set; }
        public string codigo { get; set; }
        public string articulo { get; set; }
        public string referencia { get; set; }
        public string lotnom { get; set; }
        public decimal Cant { get; set; }
        public string medida { get; set; }
        public decimal VUnit { get; set; }
        public decimal? vtot { get; set; }
        public string depnom { get; set; }
    }
}
