// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Gestion_TurnosResult
    {
        public string NomNomina { get; set; }
        public string CodNomina { get; set; }
        public decimal IdNomina { get; set; }
    }
}
