// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Informes_Contables_OTResult
    {
        public string glCod { get; set; }
        public string glnum { get; set; }
        public double? glSaldoIni { get; set; }
        public double? Debe { get; set; }
        public double? Haber { get; set; }
        public double? SaldoFin { get; set; }
        public string GRUPO { get; set; }
        public string Clasificacion { get; set; }
    }
}
