// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Cotizacion_DetResult
    {
        public string cotNum { get; set; }
        public string cotDet { get; set; }
        public string clinit { get; set; }
        public string clicod { get; set; }
        public string clinom { get; set; }
        public DateTime? cotFec { get; set; }
        public string cotCondi { get; set; }
        public string vencod { get; set; }
        public string vennom { get; set; }
        public string cotEst { get; set; }
        public string cotvali { get; set; }
        public string cotforpa { get; set; }
        public string cotgar { get; set; }
        public decimal cotdcto { get; set; }
        public decimal cotflete { get; set; }
        public decimal cotrete { get; set; }
        public string cotna { get; set; }
        public int? cotIva { get; set; }
        public decimal? cotTot { get; set; }
        public string movCod { get; set; }
        public decimal movCan { get; set; }
        public decimal movPre { get; set; }
        public string movMed { get; set; }
        public decimal movCif { get; set; }
        public decimal MovCos { get; set; }
        public decimal moviva { get; set; }
        public string MovTip { get; set; }
        public string Arespe { get; set; }
        public string clidir { get; set; }
        public string cliciud { get; set; }
        public string climail { get; set; }
        public string clitel { get; set; }
        public string movTec { get; set; }
        public string tecNom { get; set; }
        public decimal Arminimo { get; set; }
        public string MovDep { get; set; }
        public string MovEsc { get; set; }
        public string DesPre { get; set; }
        public string DepNom { get; set; }
        public string arEspecificacion { get; set; }
        public decimal cotTipoCambio { get; set; }
        public string cotcalifica { get; set; }
        public int id_unico { get; set; }
        public string dias { get; set; }
        public string marca { get; set; }
        public string CotEscala { get; set; }
        public string cotOT { get; set; }
        public DateTime cotFechaOT { get; set; }
        public string cotfactura { get; set; }
        public DateTime cotFecFactura { get; set; }
    }
}
