// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Estado_AuxiliarResult
    {
        public string masCod { get; set; }
        public string Masfec { get; set; }
        public string fteNom { get; set; }
        public string MasDoc { get; set; }
        public string masdet { get; set; }
        public decimal masIni { get; set; }
        public decimal masDeb { get; set; }
        public decimal masHbr { get; set; }
        public decimal MasSal { get; set; }
        public string GrupoNom { get; set; }
        public string SubccoNom { get; set; }
        public string Ternom { get; set; }
        public string Grupo { get; set; }
        public string Cuenta { get; set; }
        public string NomCuenta { get; set; }
        public string SubCuenta { get; set; }
        public string NomSubCuenta { get; set; }
        public string Auxiliar { get; set; }
        public string NomAuxiliar { get; set; }
        public string MasFte { get; set; }
        public DateTime fechaorden { get; set; }
        public string Indice { get; set; }
        public string TERNIT { get; set; }
        public string MasOT { get; set; }
        public decimal MasBaseRete { get; set; }
        public decimal MasPorRete { get; set; }
        public string MasTipoRete { get; set; }
    }
}
