// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_Load_exequialResult
    {
        public string nContrato { get; set; }
        public DateTime fecha { get; set; }
        public string tipo_plan { get; set; }
        public decimal valortipoliq { get; set; }
        public int Mark { get; set; }
        public decimal? descuento { get; set; }
        public string tipoplan { get; set; }
        public string codAsesor { get; set; }
    }
}
