// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_ConCombustibleResult
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string artiAsociado { get; set; }
        public string undMedida { get; set; }
        public string ctaGastoCto { get; set; }
    }
}
