// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Print_Nota_EntradaResult
    {
        public string reqord { get; set; }
        public string reqele { get; set; }
        public string arespe { get; set; }
        public string armed { get; set; }
        public string nota { get; set; }
        public decimal reqcan { get; set; }
        public decimal reqpmp { get; set; }
        public string reqfac { get; set; }
        public string reqrem { get; set; }
        public string pronom { get; set; }
        public decimal reqpre { get; set; }
        public decimal? reqdes { get; set; }
        public decimal? reqiva { get; set; }
        public decimal REQFLE { get; set; }
        public decimal? pordes { get; set; }
        public decimal poriva { get; set; }
        public decimal? reqimp { get; set; }
        public DateTime? Fecha { get; set; }
        public byte reqEst { get; set; }
        public string Estado { get; set; }
        public decimal? ivaflete { get; set; }
        public string reqDep { get; set; }
        public string referencia { get; set; }
        public string NomDependencia { get; set; }
        public string lotnom { get; set; }
        public DateTime lotfecven { get; set; }
    }
}
