// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Planilla_NominaResult
    {
        public string Nombre { get; set; }
        public decimal SalarioBase { get; set; }
        public int? Per_No_Rem { get; set; }
        public int? Dias_Lab { get; set; }
        public decimal? Tot_Sal { get; set; }
        public decimal? Aux_Trans { get; set; }
        public int? No_HED { get; set; }
        public decimal? HED { get; set; }
        public int? No_HEN { get; set; }
        public decimal? HEN { get; set; }
        public int? No_H_DOM_D { get; set; }
        public decimal? H_DOM_D { get; set; }
        public int? No_H_DOM_N { get; set; }
        public decimal? H_DOM_N { get; set; }
        public int? No_HEDD { get; set; }
        public decimal? HEDD { get; set; }
        public int? No_HEDN { get; set; }
        public decimal? HEDN { get; set; }
        public int? No_Rec_N { get; set; }
        public decimal? Rec_N { get; set; }
        public decimal? Bon { get; set; }
        public decimal? Aux_Rod { get; set; }
        public int? No_Inc_Emp { get; set; }
        public decimal? Inc_Emp { get; set; }
        public int? No_Inc_Emp2 { get; set; }
        public decimal? Inc_Emp2 { get; set; }
        public int? No_Inc_ARL { get; set; }
        public decimal? Inc_ARL { get; set; }
        public decimal? Otros_Dev { get; set; }
        public decimal? Tot_Dev { get; set; }
        public decimal? Salud { get; set; }
        public decimal? Pension { get; set; }
        public decimal? Otros_Descto { get; set; }
        public decimal? Neto_Pagar { get; set; }
        public decimal? SeguridadSocial { get; set; }
        public decimal? PrestacionesSociales { get; set; }
        public int CliFormulaDirecta { get; set; }
        public decimal CliPorcentajeLiq { get; set; }
        public int? NroIngH { get; set; }
        public int? NroIngM { get; set; }
        public int? NroRet { get; set; }
        public decimal VlrExamenIngresoM { get; set; }
        public decimal VlrExamenIngresoH { get; set; }
        public decimal VlrExamenRetiro { get; set; }
    }
}
