// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_print_ALL_cruceResult
    {
        public string recnro { get; set; }
        public string RecFuente { get; set; }
        public DateTime? recfec { get; set; }
        public string clinom { get; set; }
        public decimal? crtcli { get; set; }
        public decimal? crtpro { get; set; }
    }
}
