// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Print_Factura_DoResult
    {
        public decimal id_unico { get; set; }
        public string NOMEMP { get; set; }
        public string NITEMP { get; set; }
        public string DIREMP { get; set; }
        public string TELEMP { get; set; }
        public string NroFac { get; set; }
        public string CIUEMP { get; set; }
        public string TIPODOC { get; set; }
        public string RESOLUCION { get; set; }
        public string CODESCALA { get; set; }
        public string LOTFECVEN { get; set; }
        public string NOMCLI { get; set; }
        public string CODCLI { get; set; }
        public string DIRCLI { get; set; }
        public decimal SUBTOTALCAB { get; set; }
        public DateTime? FECHA { get; set; }
        public decimal IVA { get; set; }
        public decimal FLETE { get; set; }
        public string CLICIUD { get; set; }
        public DateTime? VENCIMIENTO { get; set; }
        public string TELCLI { get; set; }
        public string CVENDEDOR { get; set; }
        public string TPODOC { get; set; }
        public string NRODOC { get; set; }
        public decimal CANART { get; set; }
        public string MEDART { get; set; }
        public string DESART { get; set; }
        public decimal? VUNART { get; set; }
        public decimal IVAART { get; set; }
        public decimal DSUBTOTAL { get; set; }
        public decimal? subGravado { get; set; }
        public string OBSFAC { get; set; }
        public decimal rtiva { get; set; }
        public decimal rtica { get; set; }
        public decimal rtfte { get; set; }
        public string REFERENCIA { get; set; }
        public string Laboratorio { get; set; }
        public string LotNom { get; set; }
        public string codimp { get; set; }
        public string CDETALLE { get; set; }
        public decimal TOTAL { get; set; }
        public decimal TCAMBIO { get; set; }
        public decimal VLRDESCUENTO { get; set; }
        public string CODART { get; set; }
        public string marca { get; set; }
        public int pivote { get; set; }
        public decimal anticipos { get; set; }
        public string cdos { get; set; }
        public decimal valciffob { get; set; }
        public string TipMov { get; set; }
        public string pedidodo { get; set; }
        public decimal VLRFAC { get; set; }
    }
}
