// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Visualizar_LotesResult
    {
        public string Delmrk { get; set; }
        public string LotArt { get; set; }
        public string LotNom { get; set; }
        public decimal? LotCan { get; set; }
        public DateTime LotFecVen { get; set; }
        public string LotOrd { get; set; }
        public int ID { get; set; }
        public string LotFte { get; set; }
        public int LotTraslado { get; set; }
        public string LotNota { get; set; }
        public DateTime LotFecNota { get; set; }
        public int Item { get; set; }
        public decimal LotTemp { get; set; }
        public string LotObservaciones { get; set; }
        public decimal? CantLote { get; set; }
    }
}
