// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_GlCdpResult
    {
        public int id { get; set; }
        public DateTime fecha { get; set; }
        public decimal valor { get; set; }
        public string solicitante { get; set; }
        public string autorizado { get; set; }
        public string estado { get; set; }
        public string codeUsuario { get; set; }
        public string ot { get; set; }
    }
}
