// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Libro_DiarioResult
    {
        public string MasCod { get; set; }
        public string FteNom { get; set; }
        public string MasDoc { get; set; }
        public DateTime? MasFec { get; set; }
        public string MasDet { get; set; }
        public decimal? MasDeb { get; set; }
        public decimal? MasHbr { get; set; }
        public string TerNom { get; set; }
        public string cconom { get; set; }
        public string masFte { get; set; }
        public string masCco { get; set; }
        public string Nit_Tercero { get; set; }
    }
}
