// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_PlaniCombustibleResult
    {
        public bool? casilla { get; set; }
        public int ID { get; set; }
        public string placa { get; set; }
        public DateTime fecha { get; set; }
        public string operario { get; set; }
        public decimal lecturaini { get; set; }
        public decimal? lecturafin { get; set; }
        public string tl { get; set; }
        public decimal? deltaLec { get; set; }
        public decimal gnc { get; set; }
        public decimal acpm { get; set; }
        public decimal corriente { get; set; }
        public decimal premium { get; set; }
        public decimal lubricante { get; set; }
        public decimal aditivo { get; set; }
        public decimal liqfreno { get; set; }
        public decimal lecturaHini { get; set; }
        public decimal? lecturaHfin { get; set; }
        public decimal lecturakini { get; set; }
        public decimal lecturakfin { get; set; }
        public int lecturaMini { get; set; }
        public int lecturaMfin { get; set; }
        public int estado { get; set; }
        public string pronom { get; set; }
        public string nroCausacion { get; set; }
        public string comanda { get; set; }
    }
}
