// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_glPti_CFGResult
    {
        public string JefeMtto { get; set; }
        public string liderMtto { get; set; }
    }
}
