// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Compra_VerEditarResult
    {
        public decimal CostoUltCompra { get; set; }
        public decimal arcosto { get; set; }
        public decimal? CostoPost { get; set; }
    }
}
