// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Compras_ViewResult
    {
        public string REQORD { get; set; }
        public DateTime Fecha { get; set; }
        public string pronom { get; set; }
        public decimal REQVLR { get; set; }
        public string originador { get; set; }
    }
}
