// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Relacion_FacturaPosResult
    {
        public decimal ValorIva { get; set; }
        public string comdep { get; set; }
        public string nrofac { get; set; }
        public DateTime? comfec { get; set; }
        public decimal? comvlr { get; set; }
        public string clinom { get; set; }
        public string depnom { get; set; }
        public decimal? comcos { get; set; }
        public string Usuario { get; set; }
        public string arespe { get; set; }
        public decimal? comcan { get; set; }
        public decimal? comVuni { get; set; }
        public decimal? comvtot { get; set; }
        public decimal? comiva { get; set; }
        public decimal comdcto { get; set; }
        public decimal efectivo { get; set; }
        public decimal cheque { get; set; }
        public decimal tdebito { get; set; }
        public decimal tcredito { get; set; }
        public string comest { get; set; }
        public string armed { get; set; }
        public string arref { get; set; }
        public string nomcli { get; set; }
        public string codcli { get; set; }
        public string dircli { get; set; }
        public string climail { get; set; }
        public string cliciud { get; set; }
        public string telcli { get; set; }
        public int? arModalidad { get; set; }
        public string arcod { get; set; }
        public string comtipo { get; set; }
        public string clinit { get; set; }
        public string vendedor { get; set; }
        public string vennom { get; set; }
        public int ComImp { get; set; }
        public string MovDep { get; set; }
        public string CodEsc { get; set; }
        public string comMed { get; set; }
        public decimal comSub { get; set; }
        public string clicod { get; set; }
        public decimal? cliPuntos { get; set; }
    }
}
