// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_cuentas_NIIFResult
    {
        public string codcuenta { get; set; }
        public string cuenta { get; set; }
        public string pucEspejo { get; set; }
        public string aplicacion { get; set; }
        public int codigo { get; set; }
    }
}
