// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Relacion_Ant_ReteResult
    {
        public string LinCod { get; set; }
        public string RetPuc { get; set; }
        public decimal RetMon { get; set; }
        public decimal? RetPor { get; set; }
        public int? Id { get; set; }
        public int ResponIVA { get; set; }
        public string Ciudad_ICA { get; set; }
    }
}
