// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_AdjuntoFacelResult
    {
        public string nombreArchivo { get; set; }
        public string tipo { get; set; }
        public string Archivo { get; set; }
        public string ver { get; set; }
    }
}
