// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_TurnoReemplazoResult
    {
        public int Id { get; set; }
        public string Estado { get; set; }
        public string EmpleadoFijo { get; set; }
        public string EmpleadoTemporal { get; set; }
        public string Turno { get; set; }
        public string Motivo { get; set; }
        public string Detalle { get; set; }
        public decimal Valor { get; set; }
        public int Dias { get; set; }
        public decimal ValorTotal { get; set; }
    }
}
