// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_DispersionFondosResult
    {
        public bool? sel { get; set; }
        public string empCed { get; set; }
        public string empnom { get; set; }
        public DateTime? bkfec { get; set; }
        public double? bkdeb { get; set; }
        public decimal bkAnticipo { get; set; }
        public double? Saldo { get; set; }
        public string bkdet { get; set; }
        public string bk_cxp { get; set; }
        public string bannom { get; set; }
        public int id { get; set; }
        public string bkimp { get; set; }
        public string bkcco { get; set; }
        public string tipo { get; set; }
        public string bkbco { get; set; }
        public string bkcod { get; set; }
        public string cconom { get; set; }
        public string bknit { get; set; }
        public string TipoNomina { get; set; }
        public string Sucursal { get; set; }
        public string Cheque { get; set; }
        public string bkccobanco { get; set; }
        public string bkcconombanco { get; set; }
        public string bkCau { get; set; }
    }
}
