// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_planilla_combustible_totales_cuentasResult
    {
        public string nombre { get; set; }
        public string centro_costo { get; set; }
        public decimal? total { get; set; }
        public string cuenta_gasto { get; set; }
        public string ccocod { get; set; }
        public string codItem { get; set; }
    }
}
