// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_PropagosResult
    {
        public string causacion { get; set; }
        public string detalleCausacion { get; set; }
        public string estado { get; set; }
        public string factura { get; set; }
        public DateTime? fechaFactura { get; set; }
        public DateTime? fechaCausacion { get; set; }
        public string pronom { get; set; }
        public string PRONIT1 { get; set; }
        public string pronit { get; set; }
        public DateTime fechaCondicion { get; set; }
        public string condicionesPago { get; set; }
        public string Usuario { get; set; }
        public string estacion { get; set; }
        public DateTime? fechaVencidofact { get; set; }
        public decimal tcambio { get; set; }
        public decimal? saldo { get; set; }
        public decimal vlrfac { get; set; }
    }
}
