// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Control_VencimientoResult
    {
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Lote { get; set; }
        public string Dependencia { get; set; }
        public string Laboratorio { get; set; }
        public DateTime Fecha_Vence { get; set; }
        public decimal? Cantidad { get; set; }
    }
}
