// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Compras_View_NetResult
    {
        public string REQORD { get; set; }
        public DateTime REQFOR { get; set; }
        public string REQFAC { get; set; }
        public DateTime? REQFFA { get; set; }
        public string pronom { get; set; }
        public decimal? Valor_sin_Iva { get; set; }
        public decimal REQIVA { get; set; }
        public decimal REQIMP { get; set; }
        public decimal REQVLR { get; set; }
        public decimal REQDTO { get; set; }
        public decimal vTipoCambio { get; set; }
        public string reqNota { get; set; }
        public DateTime fNota { get; set; }
        public string REQCOM { get; set; }
        public string REQTEN { get; set; }
        public DateTime? FechaR { get; set; }
        public int? DiasCumpli { get; set; }
        public string Usuario_Orden { get; set; }
        public string Usuario_Autorizado { get; set; }
        public DateTime Fecha_Autorizada { get; set; }
        public string numeroOT { get; set; }
        public string pronit { get; set; }
        public int REQINV { get; set; }
        public string PRONIT { get; set; }
        public int nCompras { get; set; }
        public int ReqAutorizado { get; set; }
        public string reqestacion { get; set; }
        public DateTime reqFecServer { get; set; }
    }
}
