// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_estado_mesesResult
    {
        public string CUENTA { get; set; }
        public string DOCUMENTO { get; set; }
        public string DETALLE { get; set; }
        public decimal? DEBITO { get; set; }
        public decimal? CRÉDITO { get; set; }
        public string TERCERO { get; set; }
        public string OT { get; set; }
        public string SUBCENTROCOSTO { get; set; }
        public string CENTROCOSTO { get; set; }
    }
}
