// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_EquiposResult
    {
        public string gasnom { get; set; }
        public int dprcod { get; set; }
        public string dprnom { get; set; }
        public string clinom { get; set; }
        public string marnom { get; set; }
        public string modelo { get; set; }
        public DateTime dprfechaad { get; set; }
        public decimal dprcosto { get; set; }
        public string dprModalidad { get; set; }
        public string dprtiempodep { get; set; }
        public decimal dprcan { get; set; }
        public string dprubicacion { get; set; }
        public string dpresp { get; set; }
        public string DPRTIPO { get; set; }
        public int dpruso { get; set; }
        public string descBien { get; set; }
        public string mesnom { get; set; }
        public string pronom { get; set; }
        public string gravJuridico { get; set; }
        public string DprCco { get; set; }
        public string Poliza { get; set; }
        public string dprSerial { get; set; }
        public string zona { get; set; }
        public string estado_seguro { get; set; }
        public string enero { get; set; }
        public string febrero { get; set; }
        public string marzo { get; set; }
        public string abril { get; set; }
        public string mayo { get; set; }
        public string junio { get; set; }
        public string julio { get; set; }
        public string agosto { get; set; }
        public string septiembre { get; set; }
        public string octubre { get; set; }
        public string noviembre { get; set; }
        public string diciembre { get; set; }
    }
}
