// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_Politicas_NIIF_CONSULTARResult
    {
        public int? indice { get; set; }
        public string item { get; set; }
        public string texto { get; set; }
        public int id { get; set; }
    }
}
