// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_FiltroListPreciosResult
    {
        public string CodPre { get; set; }
        public string DesPre { get; set; }
        public string CamPre { get; set; }
    }
}
