// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_Ventas_MaroelResult
    {
        public int sel { get; set; }
        public string preventa { get; set; }
        public DateTime? fecha { get; set; }
        public string cliente { get; set; }
        public string vendedor { get; set; }
        public string solicitante { get; set; }
        public decimal? total { get; set; }
        public string cotven { get; set; }
        public string cotcli { get; set; }
    }
}
