// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Cotizacion_LotesResult
    {
        public string Cotizacion { get; set; }
        public string Articulo { get; set; }
        public string Arespe { get; set; }
        public string Dependencia { get; set; }
        public decimal? CantidadSoli { get; set; }
        public string DepNom { get; set; }
        public decimal? CantidadFac { get; set; }
        public decimal? Diferencia { get; set; }
    }
}
