// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_pedidosResult
    {
        public string Sucursal { get; set; }
        public decimal id_Sucursal { get; set; }
    }
}
