// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Consultar_KardexResult
    {
        public string KarArt { get; set; }
        public DateTime KarFec { get; set; }
        public string KarDoc { get; set; }
        public string kartip { get; set; }
        public string kardsc { get; set; }
        public string karori { get; set; }
        public string kardes { get; set; }
        public string karpro { get; set; }
        public decimal Karcan { get; set; }
        public string karmed { get; set; }
        public decimal karDeb { get; set; }
        public decimal karHbr { get; set; }
        public decimal karStk { get; set; }
        public decimal karcos { get; set; }
        public decimal karcosT { get; set; }
        public string karusr { get; set; }
        public DateTime karupd { get; set; }
        public decimal CantEqui { get; set; }
        public decimal karid { get; set; }
        public decimal karcanent { get; set; }
        public decimal karcosent { get; set; }
        public decimal karcansal { get; set; }
        public decimal karcossal { get; set; }
        public string kardocmas { get; set; }
        public string kardocest { get; set; }
        public decimal karpropon { get; set; }
        public decimal karcanact { get; set; }
        public string kartabla { get; set; }
        public string karserial { get; set; }
        public string karimei { get; set; }
        public string kariccd { get; set; }
        public decimal KarCanTotal { get; set; }
        public decimal KarCosTotal { get; set; }
        public decimal KarProPonHis { get; set; }
        public string karccosto { get; set; }
        public string karnomccosto { get; set; }
        public string karscosto { get; set; }
        public string karnomscosto { get; set; }
        public string karot { get; set; }
        public int EnConsignacion { get; set; }
        public decimal KarTemp { get; set; }
        public string arref { get; set; }
        public string HoraProceso { get; set; }
        public string Arespe { get; set; }
    }
}
