// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_print_DocEquResult
    {
        public string nrofac { get; set; }
        public string pronom { get; set; }
        public string pronit1 { get; set; }
        public string prodir { get; set; }
        public string protel { get; set; }
        public DateTime? fecfac { get; set; }
        public string nomempresa { get; set; }
        public string nitempresa { get; set; }
        public string dirempresa { get; set; }
        public string contelefono { get; set; }
        public string conciudad { get; set; }
        public string promail { get; set; }
        public string detalle { get; set; }
        public decimal vlrfac { get; set; }
        public decimal porIVA { get; set; }
        public decimal BaseIva { get; set; }
        public decimal? porRETEIVA { get; set; }
        public decimal reteiva { get; set; }
        public string nombre_regimen { get; set; }
        public string nombre_responIva { get; set; }
    }
}
