// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Conf_DescuentoCabResult
    {
        public DateTime FechaIniTel { get; set; }
        public DateTime FechaFinTel { get; set; }
        public decimal IdTele { get; set; }
        public string NomTele { get; set; }
        public string Delmrk { get; set; }
        public int ExepcionIVA { get; set; }
        public string Estado { get; set; }
    }
}
