// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Relacion_CostosResult
    {
        public string delmrk { get; set; }
        public string Codigo_Centro { get; set; }
        public string Nombre_Centro { get; set; }
        public string Codigo_Sub { get; set; }
        public string Nombre_Sub { get; set; }
        public int Seleccion { get; set; }
    }
}
