// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_ArticulosResult
    {
        public string codigo { get; set; }
        public string referencia { get; set; }
        public string CodBarrAS { get; set; }
        public string Reemplazo { get; set; }
        public string Linea { get; set; }
        public string Grupo { get; set; }
        public string marca { get; set; }
        public string Medida { get; set; }
        public string Descripcion { get; set; }
        public string EspTecnica { get; set; }
        public int TipoArti { get; set; }
        public int ParaVenta { get; set; }
        public int Pesado { get; set; }
        public int Req_Lote { get; set; }
        public int esBolsa { get; set; }
        public decimal Costo { get; set; }
        public decimal Cif { get; set; }
        public decimal Iva { get; set; }
        public decimal Escala1 { get; set; }
        public decimal Escala2 { get; set; }
        public decimal Escala3 { get; set; }
        public decimal Escala4 { get; set; }
        public decimal Prec_minimo { get; set; }
        public int Modalidad { get; set; }
        public string Imagen { get; set; }
        public int cambiarCadaK { get; set; }
        public int cambiarCadaM { get; set; }
        public int aceiteMotor { get; set; }
        public decimal Porcentaje1 { get; set; }
        public decimal Porcentaje2 { get; set; }
        public decimal Porcentaje3 { get; set; }
        public decimal Porcentaje4 { get; set; }
        public decimal PorcentajeMin { get; set; }
        public decimal ardosificacion { get; set; }
        public int arVenceDias { get; set; }
        public int ivaMayorvalor { get; set; }
        public bool ArSubProducto { get; set; }
        public string ArCodProducto { get; set; }
        public decimal artemp { get; set; }
        public string verfInvima { get; set; }
        public string conseCMU { get; set; }
        public string imgInvima { get; set; }
        public string formafarmaceuticaSYS { get; set; }
        public string laboratorioSYS { get; set; }
        public int reqRectenicaSIS { get; set; }
        public string precaucionesSYS { get; set; }
        public string RiesgoSYS { get; set; }
        public string TipoTempSYS { get; set; }
        public int ConformeSYS { get; set; }
        public decimal Artemp2 { get; set; }
        public decimal ArporDesc1 { get; set; }
        public decimal ArporDesc2 { get; set; }
        public decimal ArporDesc3 { get; set; }
        public decimal ArporDesc4 { get; set; }
        public int arConseLote { get; set; }
        public string arPrefiLote { get; set; }
        public int arDifMed { get; set; }
        public int arReqLotePro { get; set; }
    }
}
