// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_planilla_combustible_periodoResult
    {
        public int vehiculo { get; set; }
        public decimal? enero { get; set; }
        public decimal? febrero { get; set; }
        public decimal? marzo { get; set; }
        public decimal? abril { get; set; }
        public decimal? mayo { get; set; }
        public decimal? junio { get; set; }
        public decimal? julio { get; set; }
        public decimal? agosto { get; set; }
        public decimal? septiembre { get; set; }
        public decimal? octubre { get; set; }
        public decimal? noviembre { get; set; }
        public decimal? diciembre { get; set; }
        public decimal? total { get; set; }
        public string nombre { get; set; }
    }
}
