// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Print_NotasResult
    {
        public decimal? id_unico { get; set; }
        public string NOMEMP { get; set; }
        public string NITEMP { get; set; }
        public string DIREMP { get; set; }
        public string TELEMP { get; set; }
        public string NroFac { get; set; }
        public string CIUEMP { get; set; }
        public string TIPONOTA { get; set; }
        public string NOMCLI { get; set; }
        public string CODCLI { get; set; }
        public string DIRCLI { get; set; }
        public decimal SUBTOTALCAB { get; set; }
        public DateTime? FECHA { get; set; }
        public decimal IVA { get; set; }
        public string CLICIUD { get; set; }
        public string TELCLI { get; set; }
        public decimal? CANART { get; set; }
        public string MEDART { get; set; }
        public string DESART { get; set; }
        public decimal? VUNART { get; set; }
        public decimal? IVAART { get; set; }
        public decimal? DSUBTOTAL { get; set; }
        public string OBSFAC { get; set; }
        public decimal rtiva { get; set; }
        public decimal rtica { get; set; }
        public decimal rtfte { get; set; }
        public decimal TOTAL { get; set; }
        public decimal TasaCambio { get; set; }
        public string CODART { get; set; }
        public decimal saldo { get; set; }
        public string regimen { get; set; }
        public string Email { get; set; }
        public string CUFE { get; set; }
        public string CodigoQR { get; set; }
        public string MontoEscrito { get; set; }
        public long? secuencia { get; set; }
        public DateTime? FechaAprobado { get; set; }
        public string Firma { get; set; }
        public string FAC { get; set; }
        public string CUFEFAC { get; set; }
        public string FechaFC { get; set; }
        public string logempresa { get; set; }
    }
}
