// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_CxCAnalisisResult
    {
        public string tipodoc { get; set; }
        public string nombres { get; set; }
        public string nrofac { get; set; }
        public string vendedor { get; set; }
        public string vennom { get; set; }
        public string NomZona { get; set; }
        public string CliTel { get; set; }
        public DateTime? venfac { get; set; }
        public DateTime? fechaActual { get; set; }
        public string CliDir { get; set; }
        public DateTime fecfac { get; set; }
        public decimal? vlrfac { get; set; }
        public string codcli { get; set; }
        public string clitipo { get; set; }
        public string tipnom { get; set; }
        public string Calificacion { get; set; }
        public decimal? SubTotal { get; set; }
        public decimal? Valor { get; set; }
        public decimal? SALDO { get; set; }
        public DateTime FechaPago { get; set; }
        public decimal valor1 { get; set; }
        public decimal valor2 { get; set; }
        public decimal valor3 { get; set; }
        public decimal valor4 { get; set; }
        public decimal valor5 { get; set; }
        public int? Estado { get; set; }
        public int? DiasFact { get; set; }
        public int? Vencido { get; set; }
        public decimal? iva { get; set; }
        public string CliNit { get; set; }
        public string ESTADO { get; set; }
    }
}
