// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Consultar_TesoreriaResult
    {
        public string Documento { get; set; }
        public string Banco { get; set; }
        public string Cheque { get; set; }
        public string Tercero { get; set; }
        public string Fecha { get; set; }
        public DateTime? bkfec { get; set; }
        public string bknit { get; set; }
        public decimal bktipo { get; set; }
        public string bkcod { get; set; }
        public double? bkdeb { get; set; }
        public double? bkhbr { get; set; }
        public string bkbco { get; set; }
        public string bancod { get; set; }
        public string Detalle { get; set; }
        public string ModeRec { get; set; }
        public string bkfte { get; set; }
        public DateTime bkFechaCH { get; set; }
        public string UsuarioNombre { get; set; }
        public string bkcls { get; set; }
        public double? Valor { get; set; }
    }
}
