// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_VENTAS_GLResult
    {
        public string bodega { get; set; }
        public string factura { get; set; }
        public DateTime? fecha { get; set; }
        public string codigo_articulo { get; set; }
        public string nombre_articulo { get; set; }
        public decimal cantidad { get; set; }
        public decimal costo_unitario { get; set; }
        public decimal? total_pagar { get; set; }
        public string entrega { get; set; }
        public string recibe { get; set; }
        public int sel { get; set; }
        public string documento { get; set; }
        public string bodegaGL { get; set; }
        public string comar { get; set; }
        public decimal id_Unico { get; set; }
        public string comInventarios { get; set; }
    }
}
