// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Imprimir_LiquidacionResult
    {
        public string TipoNomina { get; set; }
        public DateTime? Fecha_Ini { get; set; }
        public DateTime? Fecha_Fin { get; set; }
        public string Empleado { get; set; }
        public string CodNomina { get; set; }
        public string Centro_Costo { get; set; }
        public DateTime? EmpVacAcu { get; set; }
        public DateTime? EmpUltCes { get; set; }
        public DateTime? EmpUltIntCes { get; set; }
        public DateTime? EmpUltPri { get; set; }
        public decimal NovBaseVac { get; set; }
        public decimal NovSueldoBase { get; set; }
        public decimal NovTransporte { get; set; }
        public decimal NovExtra { get; set; }
        public decimal NovExtraPrima { get; set; }
        public decimal NovExtraVaca { get; set; }
        public string NovMotivo { get; set; }
        public decimal Novdhc { get; set; }
        public decimal NovIbc { get; set; }
        public decimal NovDeb { get; set; }
        public string novnom { get; set; }
        public string Cargo { get; set; }
        public decimal? DiasCes { get; set; }
        public decimal? DiasIntCes { get; set; }
        public decimal? DiasPri { get; set; }
        public decimal? DiasVac { get; set; }
        public decimal? Deducciones { get; set; }
        public string EmpNom { get; set; }
        public string EmpCed { get; set; }
        public int NovTipo { get; set; }
        public string TIPO_MODALIDAD { get; set; }
        public string conciudad { get; set; }
        public int? DiaSuspension { get; set; }
        public int? DiasCalendariosSobre { get; set; }
    }
}
