// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_print_cruceResult
    {
        public string recFac { get; set; }
        public DateTime? fecFac { get; set; }
        public decimal vlrfac { get; set; }
        public decimal recvlr { get; set; }
        public decimal recdescto { get; set; }
        public decimal recrtiva { get; set; }
        public decimal recrtica { get; set; }
        public decimal recrtfte { get; set; }
        public decimal? recSal { get; set; }
        public int Tipo { get; set; }
        public string recTip { get; set; }
        public DateTime? recfec { get; set; }
        public string recCli { get; set; }
        public decimal anticipos { get; set; }
    }
}
