// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_TipoDocResult
    {
        public string docCod { get; set; }
        public string docNam { get; set; }
        public string docFte { get; set; }
    }
}
