// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Solicitud_RetencionResult
    {
        public string IDENTIFICACION_CLIENTE { get; set; }
        public string NOMRBRE_CLIENTE { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
        public string TELEFONO_CLIENTE { get; set; }
        public int SEL { get; set; }
    }
}
