// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_informe_compras_periodoResult
    {
        public string REQCON { get; set; }
        public string nrocxp { get; set; }
        public string nrofac { get; set; }
        public string nombres { get; set; }
        public DateTime? fecfac { get; set; }
        public decimal total { get; set; }
        public decimal? totiva { get; set; }
        public decimal? vlrrtf { get; set; }
        public decimal? vlrica { get; set; }
        public decimal? vlrrti { get; set; }
    }
}
