// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Get_MonedaResult
    {
        public string delmrk { get; set; }
        public DateTime? fecha { get; set; }
        public decimal valor { get; set; }
        public string Codigo { get; set; }
        public string TipoMoneda { get; set; }
    }
}
