// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_Politicas_NIIF_CONSULTAR_textoResult
    {
        public string texto { get; set; }
    }
}
