// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_ccArti2Result
    {
        public string arcod { get; set; }
        public string ARESPE { get; set; }
        public decimal arcosto { get; set; }
        public string ARREF { get; set; }
        public decimal? ArIva { get; set; }
        public double? Existencia { get; set; }
        public string ARMED { get; set; }
        public string remplazo { get; set; }
        public int artipoar { get; set; }
        public decimal PrecioMinimo { get; set; }
        public string armar { get; set; }
        public decimal Minimo { get; set; }
        public int Arlote { get; set; }
        public decimal arDosificacion { get; set; }
        public string CtaInventario { get; set; }
        public string ArEspecificacion { get; set; }
        public string CtaCosto { get; set; }
        public string CtaIngreso { get; set; }
        public decimal arventa { get; set; }
        public decimal ArDisco { get; set; }
        public decimal ArEven { get; set; }
        public decimal ArPrecio { get; set; }
        public int ArModalidad { get; set; }
        public decimal Maximo { get; set; }
        public string ARSECTOR { get; set; }
        public decimal ARMINIMO { get; set; }
        public decimal? PRECIO { get; set; }
        public decimal arporpre1 { get; set; }
        public decimal arporpre2 { get; set; }
        public decimal arporpre3 { get; set; }
        public decimal arporpre4 { get; set; }
        public decimal arporpremin { get; set; }
        public int Arpesado { get; set; }
    }
}
