// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_usuariosResult
    {
        public string Codigo { get; set; }
        public string Usuario { get; set; }
        public string nombre { get; set; }
        public string TipNom { get; set; }
        public string empNom { get; set; }
        public string depnom { get; set; }
        public bool? UsarAPP { get; set; }
        public bool? userCliente { get; set; }
    }
}
