// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Rpt_ReqinternaResult
    {
        public string Codigo { get; set; }
        public string Articulo { get; set; }
        public string medidaReal { get; set; }
        public decimal Costo { get; set; }
        public decimal Iva { get; set; }
        public decimal? Solicitado { get; set; }
        public decimal? EXISTENCIA { get; set; }
        public decimal? cantidadFalta { get; set; }
    }
}
