// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_RptFicTecVehResult
    {
        public string Placa { get; set; }
        public string Modelo { get; set; }
        public string Cilindraje { get; set; }
        public string chasis { get; set; }
        public string NroMotor { get; set; }
        public string TipoCombustible { get; set; }
        public string Color { get; set; }
        public string Marca { get; set; }
        public string Linea { get; set; }
        public string Empresa { get; set; }
        public string Propietario { get; set; }
        public string ConseRunt { get; set; }
        public string TipoServicio { get; set; }
        public string Clase { get; set; }
        public string Aseguradora1 { get; set; }
        public string poliza1 { get; set; }
        public DateTime? venceaseguradora1 { get; set; }
        public string TipoPoliza { get; set; }
        public string Aseguradora2 { get; set; }
        public string poliza2 { get; set; }
        public DateTime? venceaseguradora2 { get; set; }
        public string PlacaTrailer { get; set; }
        public string NroSerie { get; set; }
        public string PlacaSR { get; set; }
        public decimal PesoSC { get; set; }
        public string ModeloRep { get; set; }
        public string RNC { get; set; }
        public string Tprop { get; set; }
        public string Anombre { get; set; }
        public string Conductor { get; set; }
        public string Carroceria { get; set; }
        public string Configuracion { get; set; }
        public string Soat { get; set; }
        public DateTime? Vsoat { get; set; }
        public string EGases { get; set; }
        public DateTime? VEgases { get; set; }
        public string EGas { get; set; }
        public DateTime? VEGas { get; set; }
        public string CRTM { get; set; }
        public DateTime? VCRTM { get; set; }
        public string TarOpe { get; set; }
        public DateTime? vTarOpe { get; set; }
        public string configuracion { get; set; }
        public int pertenencia { get; set; }
        public int numejes { get; set; }
        public decimal capcarga { get; set; }
        public decimal largo { get; set; }
        public decimal ancho { get; set; }
        public decimal profundidad { get; set; }
        public string usuariogps { get; set; }
        public string contraseniagps { get; set; }
        public string Licencia { get; set; }
        public DateTime? LicVence { get; set; }
        public decimal? horometroInicial { get; set; }
    }
}
