// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_ConsultarCarteraPendienteResult
    {
        public string nFactura { get; set; }
        public string Tipo { get; set; }
        public string fecfac { get; set; }
        public string fechavence { get; set; }
        public int venfac { get; set; }
        public string diasvence { get; set; }
        public string cliente { get; set; }
        public decimal? subIva { get; set; }
        public decimal Iva { get; set; }
        public decimal? dscto { get; set; }
        public decimal vrCredito { get; set; }
        public decimal? total { get; set; }
        public decimal Abono { get; set; }
        public decimal? Retenciones { get; set; }
        public decimal Saldo { get; set; }
        public decimal nDevoluciones { get; set; }
        public decimal nIvaDev { get; set; }
        public string detalle { get; set; }
    }
}
