// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Conf_DescuentoDetResult
    {
        public string ArCod { get; set; }
        public string Arespe { get; set; }
        public decimal Descuento { get; set; }
        public string Importado { get; set; }
        public int IdTeleCab { get; set; }
        public string NomTele { get; set; }
        public DateTime FechaIniTel { get; set; }
        public DateTime FechaFinTel { get; set; }
        public int Import { get; set; }
    }
}
