// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Liquidacion_PrestacionesResult
    {
        public string CodigoEmp { get; set; }
        public string NOMBRE { get; set; }
        public string CEDULA { get; set; }
        public DateTime? FECHA_INGRESO { get; set; }
        public decimal? SUELDO { get; set; }
        public decimal TRANSPORTE { get; set; }
        public decimal? PROMEDIO_HORAS_EXTRTA { get; set; }
        public int? DIAS_LABORADOS { get; set; }
        public decimal? Promedio_Devengado { get; set; }
        public int Valor_Prima { get; set; }
        public string empcodprimas { get; set; }
        public string empccosto { get; set; }
        public string empcodvacaciones { get; set; }
        public string empcodintcesantias { get; set; }
        public string empcodcesantias { get; set; }
        public string empCodPrimaConvencional { get; set; }
        public string empCodPrimaVacacional { get; set; }
        public string empcodasal { get; set; }
        public string empcodapen { get; set; }
        public DateTime EmpUltPri { get; set; }
        public decimal? BASE { get; set; }
    }
}
