// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_HorariosTurnosResult
    {
        public string EmpCed { get; set; }
        public string EmpNom { get; set; }
        public string HorOrdNro { get; set; }
        public string NombreSubCentro { get; set; }
        public decimal EmpValorHr { get; set; }
        public DateTime? EmpFe1 { get; set; }
        public DateTime? EmpFe2 { get; set; }
        public decimal EmpHNOR { get; set; }
        public decimal EmpTransporte { get; set; }
        public decimal EmpBon { get; set; }
        public decimal EmpHNorFest { get; set; }
        public decimal EmpHRENO { get; set; }
        public decimal EmpHEOD { get; set; }
        public decimal EmpHEON { get; set; }
        public decimal HORRENOF { get; set; }
        public decimal EmpHEFD { get; set; }
        public decimal EmpHEFN { get; set; }
        public decimal EmpCom { get; set; }
        public string empcod { get; set; }
        public int empTurnos { get; set; }
        public int ident { get; set; }
        public string CodigoSubCentro { get; set; }
    }
}
