// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_ArchivoBancosResult
    {
        public string Identificador { get; set; }
        public long? Secuencia { get; set; }
        public DateTime? Fecha_Movimiento { get; set; }
        public string Tipo_Documento_Tercero { get; set; }
        public string Nit_Tercero { get; set; }
        public string Nombre_Tercero { get; set; }
        public string Señal { get; set; }
        public string Oficina_Cheque { get; set; }
        public string Banco_Tercero { get; set; }
        public string Tipo_Cuenta_Tercero { get; set; }
        public string Numero_Cuenta_Tercero { get; set; }
        public string Tipo_Transaccion { get; set; }
        public decimal? Valor_Transaccion { get; set; }
        public string Referencia_Transaccion { get; set; }
        public string Observacion_Transaccion { get; set; }
        public string Mail_Tercero { get; set; }
        public string Telefono_Tercero { get; set; }
        public string Telefono2_Tercero { get; set; }
        public string Fax_Tercero { get; set; }
        public string Direccion_Tercero { get; set; }
        public string Pais_Tercero { get; set; }
        public string Departamento_Tercero { get; set; }
        public string Ciudad_Tercero { get; set; }
        public string Tipo_Documento_Empresa { get; set; }
        public string Nit_Empresa { get; set; }
        public string Tipo_Cuenta_Empresa { get; set; }
        public string Cuenta_Empresa { get; set; }
        public string CODIGO_PUC { get; set; }
    }
}
