// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Comparar_Cartera_ContaResult
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public decimal? SaldoCartera { get; set; }
        public decimal? SaldoContabilidad { get; set; }
        public decimal? Diferencia { get; set; }
    }
}
