// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_ListarArticulosResult
    {
        public string codarticulo { get; set; }
        public string nombreArticulo { get; set; }
        public string dependencia { get; set; }
        public string linea { get; set; }
        public string medida { get; set; }
        public string referencia { get; set; }
        public decimal acantidad { get; set; }
        public decimal costo { get; set; }
        public string marcas { get; set; }
        public decimal? total { get; set; }
        public string LOTNOM { get; set; }
        public string LOTART { get; set; }
        public decimal LOTCAN { get; set; }
        public DateTime LOTFECVEN { get; set; }
    }
}
