// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_FormatosResult
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Idarchivo { get; set; }
        public decimal Id { get; set; }
        public decimal Tope { get; set; }
        public string Versionn { get; set; }
    }
}
