// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Compra_IngecoolResult
    {
        public string CUENTA { get; set; }
        public DateTime? FECHA { get; set; }
        public string NIT { get; set; }
        public string PROVEEDOR { get; set; }
        public string FACTURA { get; set; }
        public decimal COMPRA { get; set; }
        public decimal? IVA { get; set; }
        public decimal? RETFTE { get; set; }
        public decimal? RETEICA { get; set; }
        public decimal? RETEIVA { get; set; }
        public decimal TOTAL_A_PAGAR { get; set; }
        public string GRAVADO { get; set; }
        public string Tipo { get; set; }
    }
}
