// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_Load_Articulos_Cotizacion_FilaResult
    {
        public string movcod { get; set; }
        public string movdet { get; set; }
        public decimal movcan { get; set; }
        public string MovMed { get; set; }
        public decimal movcos { get; set; }
    }
}
