// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Orden_ContratacionResult
    {
        public string ReqFac { get; set; }
        public string reqord { get; set; }
        public string reqnro { get; set; }
        public string Nota { get; set; }
        public string pronom { get; set; }
        public string reqfor { get; set; }
        public decimal? reqvlrtot { get; set; }
        public decimal reqiva { get; set; }
        public decimal reqdto { get; set; }
        public decimal reqvlr { get; set; }
        public decimal? porcentaje_orden { get; set; }
        public int reqInv { get; set; }
        public string reqtyp { get; set; }
        public string reqcer { get; set; }
        public string reqpro { get; set; }
        public string Moneda { get; set; }
        public decimal tipoCambio { get; set; }
        public bool excluido { get; set; }
        public string reqCCo { get; set; }
        public string ReqDep { get; set; }
        public string depnom { get; set; }
        public string reqOri { get; set; }
        public DateTime fecha_orden_contra { get; set; }
        public string Originador { get; set; }
        public decimal reqImp { get; set; }
        public string numeroOT { get; set; }
        public DateTime fecha_req { get; set; }
    }
}
