// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Anticipos_NominaResult
    {
        public string empced { get; set; }
        public string empnom { get; set; }
        public DateTime? FecObligacion { get; set; }
        public string connom { get; set; }
        public decimal VlrObligacion { get; set; }
        public decimal PjeObligacion { get; set; }
        public int NroCuotas { get; set; }
        public decimal SaldoObligacion { get; set; }
        public string NomEstado { get; set; }
        public string Documento_Desembolso { get; set; }
        public string Fuente_Desembolso { get; set; }
        public string FteNom { get; set; }
        public string conCod { get; set; }
        public string CodEmpleado { get; set; }
        public string CodConcepto { get; set; }
        public int Estado { get; set; }
        public string PucObligacion { get; set; }
        public int PagarEn { get; set; }
        public int GeneraEgreso { get; set; }
        public int CodObligacion { get; set; }
        public decimal Id_Dispersion { get; set; }
    }
}
