// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Ejecutar_Archivo_SqlResult
    {
        public string name { get; set; }
        public int? minimum { get; set; }
        public int? maximum { get; set; }
        public int? config_value { get; set; }
        public int? run_value { get; set; }
    }
}
