// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Orden_Contratacion_DETALLADOResult
    {
        public string reqele { get; set; }
        public string arespe { get; set; }
        public string armed { get; set; }
        public decimal Solicitado { get; set; }
        public decimal Recibido { get; set; }
        public decimal? Pendiente { get; set; }
        public decimal nuevaCant { get; set; }
        public int Seleccionar { get; set; }
        public decimal valor_entrega { get; set; }
        public decimal iva_entrega { get; set; }
        public decimal? porcentaje_item { get; set; }
        public decimal valorRecibido { get; set; }
        public decimal? arcosto { get; set; }
        public decimal? reqVlr { get; set; }
        public decimal reqiva { get; set; }
        public decimal porIva { get; set; }
        public decimal porDes { get; set; }
        public string reqord { get; set; }
        public int arlote { get; set; }
        public decimal reqdes { get; set; }
        public decimal reqimp { get; set; }
        public string reqpro { get; set; }
        public decimal REQPRECIO { get; set; }
        public decimal reqPrecio2 { get; set; }
        public decimal ReqPrecio3 { get; set; }
        public decimal ReqPrecio4 { get; set; }
        public decimal ReqMinimo { get; set; }
        public int Facturado { get; set; }
        public int ReqRec2 { get; set; }
        public decimal ReqPmp { get; set; }
        public string ReqNota { get; set; }
        public int REQTIPIVA { get; set; }
        public decimal? reqPen { get; set; }
        public decimal? subtotal { get; set; }
        public decimal reqrec { get; set; }
        public string CUENTA { get; set; }
    }
}
