// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_CotizacionResult
    {
        public string cotNum { get; set; }
        public string clinom { get; set; }
        public DateTime? cotFec { get; set; }
        public decimal? cotTot { get; set; }
        public decimal cotTipoCambio { get; set; }
        public string cotCalifica { get; set; }
        public string dias { get; set; }
        public string cotfactura { get; set; }
        public string cotFecFactura { get; set; }
        public string cotOT { get; set; }
        public string cotFechaOT { get; set; }
        public string cotDet { get; set; }
        public string clinit { get; set; }
        public string clicod { get; set; }
        public string cotCondi { get; set; }
        public string vencod { get; set; }
        public string vennom { get; set; }
        public string cotEst { get; set; }
        public string cotvali { get; set; }
        public string cotforpa { get; set; }
        public string cotgar { get; set; }
        public decimal cotdcto { get; set; }
        public decimal cotflete { get; set; }
        public decimal cotrete { get; set; }
        public string cotna { get; set; }
        public int? cotIva { get; set; }
        public string clidir { get; set; }
        public string clitel { get; set; }
        public string cliciud { get; set; }
        public string climail { get; set; }
        public string CotEscala { get; set; }
    }
}
