// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class proc_buscarHeadSeguiResult
    {
        public string cotnum { get; set; }
        public string cotdet { get; set; }
        public string cotot { get; set; }
        public string cotfechaot { get; set; }
        public string cotfactura { get; set; }
        public string cotfecfactura { get; set; }
        public DateTime? cotfec { get; set; }
        public string CICLO { get; set; }
    }
}
