// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Print_ConciliacionResult
    {
        public string cod { get; set; }
        public string NOMBRE { get; set; }
        public string med { get; set; }
        public double? difer { get; set; }
        public decimal precio { get; set; }
        public decimal smin { get; set; }
        public decimal smax { get; set; }
        public decimal sact { get; set; }
        public decimal cantfis { get; set; }
        public string NUMERO { get; set; }
        public string DEPENDENCIA { get; set; }
        public string Referencia { get; set; }
    }
}
