// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_Datos_RetencionResult
    {
        public string CodPuc { get; set; }
        public string Codigo { get; set; }
        public string Tipo { get; set; }
    }
}
