// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_PrefacturasResult
    {
        public string Documento { get; set; }
        public string Cliente { get; set; }
        public string CodCliente { get; set; }
        public DateTime Fecha { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Iva { get; set; }
        public decimal Descuento { get; set; }
        public decimal Total { get; set; }
        public string Usuario { get; set; }
        public DateTime FechaCreacion { get; set; }
        public string Dependencia { get; set; }
    }
}
