// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class Proc_AusentismosResult
    {
        public string empNom { get; set; }
        public string empCed { get; set; }
        public string NomAus { get; set; }
        public DateTime Fecha { get; set; }
        public int id_unico { get; set; }
        public DateTime Fecha1 { get; set; }
        public DateTime Fecha2 { get; set; }
        public string MovNom { get; set; }
        public string MovCod { get; set; }
        public string Fecha_Radicado { get; set; }
        public string Empresa { get; set; }
        public string EPS { get; set; }
        public string Prorroga { get; set; }
        public string NroIncapacidad { get; set; }
        public int? Dias { get; set; }
        public string RegEstado { get; set; }
        public long? Numero { get; set; }
    }
}
