// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class remision_concre_acerosResult
    {
        public string Codigo { get; set; }
        public string Articulo { get; set; }
        public string Medida { get; set; }
        public decimal Cant { get; set; }
        public decimal remlongitud { get; set; }
        public decimal vunit { get; set; }
        public string remforma { get; set; }
        public string DepNom { get; set; }
        public string RemEsc { get; set; }
        public string remdiametro { get; set; }
        public decimal rempeso { get; set; }
        public decimal remvalorpeso { get; set; }
        public decimal remvalorlong { get; set; }
        public decimal RemValorUnid { get; set; }
        public decimal VTot { get; set; }
        public string escala { get; set; }
        public string referencia { get; set; }
        public string remcod { get; set; }
        public string RemDepe { get; set; }
        public decimal arMinimo { get; set; }
        public string arMed { get; set; }
        public decimal id_unico { get; set; }
        public decimal Equivalencia { get; set; }
        public decimal RemCosto { get; set; }
        public string vencod { get; set; }
        public string vennom { get; set; }
        public string dircli { get; set; }
        public string telcli { get; set; }
        public string remDet { get; set; }
        public decimal factor { get; set; }
    }
}
