// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class S_ACCGLMASResult
    {
        public decimal? MASDEB { get; set; }
        public decimal? MASHBR { get; set; }
        public DateTime? MASFEC { get; set; }
        public string MASCOD { get; set; }
    }
}
