// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class seriales_disponiblesResult
    {
        public string empleado { get; set; }
        public string nomare { get; set; }
        public string fecha { get; set; }
        public string serial { get; set; }
        public int seleccionado { get; set; }
        public int viejo { get; set; }
    }
}
