// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using generalapi.Models;

namespace generalapi.Models
{
    public partial class SISMEDICAERPContext : DbContext
    {
        public SISMEDICAERPContext()
        {
        }

        public SISMEDICAERPContext(DbContextOptions<SISMEDICAERPContext> options)
            : base(options)
        {
        }

       

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("SQL_1xCompat_CP850_CI_AS");
            //modelBuilder.Entity<AAAGlapp_SP_DrugsDeliveryConsumerViewArticlesBorrarResult>().HasNoKey().ToView(null);
            //modelBuilder.Entity<APP_SP_DrugsDeliveryConsumerViewHeaderResult>().HasNoKey().ToView(null);
            //modelBuilder.Entity<APP_SP_DrugsDeliveryConsumerViewHeaderResult>().HasNoKey();
            //modelBuilder.Entity<APP_SP_DrugsDeliveryConsumerViewHeaderResult>().HasNoKey();


            
            modelBuilder.Entity<APP_SP_DrugsDeliveryConsumerViewHeaderResult>(entity =>
            {
                entity.HasKey(e => e.License)
                    .HasName("PK__products__1E5A0B8E2D96C866");
                //entity.ToTable("acccccxc");
                //entity.
                entity.Property(e => e.License).HasColumnName("License");
                /*
                entity.Property(e => e.Consumer)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("Consumer");
                */
            });
            
            

            /*
            modelBuilder.Entity<Glapp_SP_DrugsDeliveryConsumerViewArticlesResult>(entity =>
            {
                entity.HasKey(e => e.ArticleCode)
                    .HasName("PK__products__1E5A0B8E2D96C866");
            });
            */


            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        public DbSet<generalapi.Models.APP_SP_DrugsDeliveryConsumerViewHeaderResult> APP_SP_DrugsDeliveryConsumerViewHeaderResult { get; set; }
    }
}