// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace generalapi.Models
{
    public partial class SISMEDICAERPContext : DbContext
    {
        public SISMEDICAERPContext()
        {
        }

        public SISMEDICAERPContext(DbContextOptions<SISMEDICAERPContext> options)
            : base(options)
        {
        }

        public virtual DbSet<GlappDrugsDeliveryConsumptionDet> GlappDrugsDeliveryConsumptionDets { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("SQL_1xCompat_CP850_CI_AS");

            modelBuilder.Entity<GlappDrugsDeliveryConsumptionDet>(entity =>
            {
                entity.HasKey(e => e.ConsumptionDetailId)
                    .HasName("PK_glapp_drugs_consumption_det_id");

                entity.ToTable("GlappDrugsDeliveryConsumptionDet");

                entity.Property(e => e.ConsumptionDetailId).HasColumnName("ConsumptionDetailID");

                entity.Property(e => e.ArticleCode)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.ConsumptionId).HasColumnName("ConsumptionID");

                entity.Property(e => e.CreationDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Delivered).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.Quantity).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.UnitOfMeasure)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}