// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_AuditoriaIvaResult
    {
        public string DocCierre { get; set; }
        public string FteCierre { get; set; }
        public DateTime? Masfec { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFinal { get; set; }
        public decimal? ModuloIngExento { get; set; }
        public decimal? ContabilidadIngExento { get; set; }
        public decimal? ModuloIngGravado { get; set; }
        public decimal? ContabilidadIngGravado { get; set; }
        public decimal? ModuloIva { get; set; }
        public decimal? ContabilidadIva { get; set; }
    }
}
