// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_ArticuloLotesResult
    {
        public string Codigo { get; set; }
        public string ESPECIFI { get; set; }
        public string MEDIDA { get; set; }
        public string Dependencia { get; set; }
        public string LoteNomb { get; set; }
        public decimal? CantArt { get; set; }
        public decimal CantidadLote { get; set; }
        public DateTime? Fecha_Vence { get; set; }
        public decimal? Diferencia { get; set; }
        public decimal Costo { get; set; }
    }
}
