// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_BKCHPOSTResult
    {
        public string Cheque { get; set; }
        public string nomBan { get; set; }
        public DateTime fecha { get; set; }
        public decimal? Valor { get; set; }
        public string Cliente { get; set; }
        public int Estado { get; set; }
        public int id { get; set; }
        public string Banco { get; set; }
    }
}
