// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_COMPROBANTE_PAGOResult
    {
        public string novemp { get; set; }
        public string empNom { get; set; }
        public string novcon { get; set; }
        public string novnom { get; set; }
        public decimal novdhc { get; set; }
        public decimal novdeb { get; set; }
        public string novpuc { get; set; }
        public DateTime? novini { get; set; }
        public DateTime? novfin { get; set; }
        public int rompimiento { get; set; }
        public string NovEnti { get; set; }
        public string Entidad { get; set; }
        public string empEmail { get; set; }
        public int novobl { get; set; }
        public decimal Saldo { get; set; }
        public string NomCargo { get; set; }
        public string TipoNomina { get; set; }
    }
}
