// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_CWIvaResult
    {
        public string Item { get; set; }
        public string Factura { get; set; }
        public DateTime? Fecha { get; set; }
        public string Producto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal? ValorUnitario { get; set; }
        public decimal? Total { get; set; }
        public decimal Tarifa { get; set; }
        public decimal? Iva { get; set; }
        public string Cuenta { get; set; }
        public string Tipo { get; set; }
    }
}
