// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_CORTE_CARTERAResult
    {
        public string NROFAC { get; set; }
        public string TIPODOC { get; set; }
        public DateTime FECFAC { get; set; }
        public string CLINOM { get; set; }
        public decimal? VLRFAC { get; set; }
        public decimal? ABONO { get; set; }
        public decimal? SALDO { get; set; }
        public string ESTADO { get; set; }
        public string NEGOCIO { get; set; }
        public string CIUDAD { get; set; }
        public string VENDEDOR { get; set; }
        public string TipoCliente { get; set; }
    }
}
