// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_Causar_CombustibleResult
    {
        public string masdoc { get; set; }
        public DateTime? masfec { get; set; }
        public string masdet { get; set; }
        public string mascod { get; set; }
        public decimal? masdeb { get; set; }
        public int mashbr { get; set; }
        public string mascco { get; set; }
        public string master { get; set; }
    }
}
