// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_ConsultaPosResult
    {
        public string nomDependencia { get; set; }
        public string numfact { get; set; }
        public DateTime? Fecha { get; set; }
        public string nomCliente { get; set; }
        public string DirCli { get; set; }
        public string TelCli { get; set; }
        public string nomCli { get; set; }
        public string clinit { get; set; }
        public string cCajero { get; set; }
        public string vennom { get; set; }
        public string nomart { get; set; }
        public string medidabase { get; set; }
        public string Referencia { get; set; }
        public decimal Cantidad { get; set; }
        public decimal? Vuni { get; set; }
        public decimal? vTot { get; set; }
        public decimal vlrIva { get; set; }
        public decimal Iva { get; set; }
        public decimal vlrImp { get; set; }
        public decimal Imp { get; set; }
        public decimal Subtotal2 { get; set; }
        public decimal Descuento { get; set; }
        public decimal Iva2 { get; set; }
        public decimal? valorTotal { get; set; }
        public decimal comvlrimpo { get; set; }
        public decimal? cancela { get; set; }
        public decimal? Vuelto { get; set; }
        public decimal Bono { get; set; }
        public decimal cheque { get; set; }
        public decimal tDebito { get; set; }
        public decimal tCredito { get; set; }
        public decimal valCredito { get; set; }
        public decimal efectivo { get; set; }
        public int puntos_factura { get; set; }
        public int puntos_acum_total { get; set; }
        public int puntos_redimidos { get; set; }
        public decimal descuentohvp { get; set; }
        public string CliCod { get; set; }
        public decimal Clipuntos { get; set; }
        public string Sw { get; set; }
        public string LotNom { get; set; }
        public DateTime LotFecVen { get; set; }
        public string marnom { get; set; }
        public string CIUCLI { get; set; }
        public string venCod { get; set; }
        public decimal? comvuni { get; set; }
        public decimal? comvtot { get; set; }
        public string movesc { get; set; }
        public string estadofactura { get; set; }
        public decimal? baseIva { get; set; }
        public decimal id_unico { get; set; }
        public string remitente { get; set; }
        public string mail { get; set; }
        public decimal valorINC { get; set; }
        public int TipoImpuesto { get; set; }
        public string resolucion { get; set; }
        public decimal? regimen { get; set; }
        public string TituloFactura { get; set; }
        public decimal RETE2 { get; set; }
        public decimal RETEFTE2 { get; set; }
        public decimal RETEICA2 { get; set; }
        public decimal RETEIVA2 { get; set; }
        public string comCod { get; set; }
    }
}
