// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_GetMenuResult
    {
        public string Codigo { get; set; }
        public string Caption { get; set; }
        public string TipoComando { get; set; }
        public string Comando { get; set; }
        public string Padre { get; set; }
    }
}
