// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_GetInventoryCountListUsersToShareResult
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string USUARIO { get; set; }
        public bool? APROBAR { get; set; }
    }
}
