// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_Imp_FacturaResult
    {
        public int Item { get; set; }
        public int StdArt { get; set; }
        public string tipodoc { get; set; }
        public string codcli { get; set; }
        public DateTime fecha { get; set; }
        public int vence { get; set; }
        public string tpodoc { get; set; }
        public string nrodoc { get; set; }
        public decimal feeban { get; set; }
        public string nrofac { get; set; }
        public string codart { get; set; }
        public string medart { get; set; }
        public string desart { get; set; }
        public decimal canart { get; set; }
        public decimal? Vunart { get; set; }
        public decimal? Vtoart { get; set; }
        public decimal total { get; set; }
        public string telcli { get; set; }
        public string dircli { get; set; }
        public string nomcli { get; set; }
        public decimal subtotal { get; set; }
        public decimal dcto { get; set; }
        public decimal iva { get; set; }
        public string ciucli { get; set; }
        public decimal flete { get; set; }
        public decimal Ivaart { get; set; }
        public int modelo { get; set; }
        public int pivote { get; set; }
        public string VenCod { get; set; }
        public string DepCod { get; set; }
        public string CodEscala { get; set; }
        public decimal TCambio { get; set; }
        public decimal? retenciones { get; set; }
        public string REFERENCIA { get; set; }
        public string Detalle { get; set; }
        public string CodImp { get; set; }
        public string CliCod { get; set; }
        public string TipDoc { get; set; }
        public decimal VlrDescuento { get; set; }
    }
}
