// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_Load_HorasResult
    {
        public string horaIni { get; set; }
        public string horaFin { get; set; }
    }
}
