// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_MovAuxTerResult
    {
        public string mascod { get; set; }
        public string glnum { get; set; }
        public DateTime Masfec { get; set; }
        public string masfte { get; set; }
        public string masdoc { get; set; }
        public string masdet { get; set; }
        public string TerCod { get; set; }
        public string TerNit { get; set; }
        public string TerNom { get; set; }
        public decimal? masdeb { get; set; }
        public decimal? mashbr { get; set; }
        public decimal? nuevoSaldo { get; set; }
        public int nPrint { get; set; }
        public decimal? SalAnt { get; set; }
    }
}
