// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_MasoldResult
    {
        public string clase { get; set; }
        public string grupo { get; set; }
        public string cuenta { get; set; }
        public string subcuenta { get; set; }
        public string nombreCuenta { get; set; }
        public string nombreSubcuenta { get; set; }
        public string nombreGrupo { get; set; }
        public string nombreClase { get; set; }
        public string mascod { get; set; }
        public string GLNUM { get; set; }
        public DateTime? masfec { get; set; }
        public string masdoc { get; set; }
        public string masfte { get; set; }
        public string masdet { get; set; }
        public decimal MASDEB { get; set; }
        public decimal MASHBR { get; set; }
        public decimal? saldo { get; set; }
        public string ternom { get; set; }
        public decimal? glbal { get; set; }
        public string Estructura { get; set; }
        public string codEstructura { get; set; }
        public string MASCCO { get; set; }
        public string cconom { get; set; }
        public string master { get; set; }
        public string ternit { get; set; }
    }
}
