// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_NominasCausadasResult
    {
        public string EmpCed { get; set; }
        public string EmpNom { get; set; }
        public string NomNomb { get; set; }
        public string NovNom { get; set; }
        public string Periodo { get; set; }
        public decimal NovDhc { get; set; }
        public string TipoConcepto { get; set; }
        public decimal? NovDeb { get; set; }
        public DateTime? NovIni { get; set; }
        public DateTime? NovFin { get; set; }
        public string ConCod { get; set; }
    }
}
