// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_Pedido_DetalleResult
    {
        public string TipoMov { get; set; }
        public string CodArti { get; set; }
        public string DesArti { get; set; }
        public string Referencia { get; set; }
        public string Medida { get; set; }
        public decimal Cantidad { get; set; }
        public decimal vUni { get; set; }
        public decimal ariva { get; set; }
        public decimal nDesc { get; set; }
        public decimal dsubtotal { get; set; }
        public decimal ComVlrIva { get; set; }
        public string dependencia { get; set; }
        public string Linea { get; set; }
        public string Grupo { get; set; }
        public string Marca { get; set; }
        public string nroFac { get; set; }
        public string TipoDoc { get; set; }
        public string comequ { get; set; }
        public decimal comcos { get; set; }
        public decimal id_unico { get; set; }
        public string ctainv { get; set; }
        public string ctacos { get; set; }
        public string ctaing { get; set; }
        public int? IvaInc { get; set; }
        public string arBarras { get; set; }
        public decimal existencia { get; set; }
        public decimal canFac { get; set; }
    }
}
