// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_pedidosResult
    {
        public string nFactura { get; set; }
        public DateTime Fecha { get; set; }
        public string cliente { get; set; }
        public decimal subIva { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public decimal vDesc { get; set; }
        public decimal Flete { get; set; }
        public decimal? neto { get; set; }
        public string Vendedor { get; set; }
        public string Zona { get; set; }
        public string ciudad { get; set; }
        public string clicod { get; set; }
        public string clicontac2 { get; set; }
        public string cliCodCiud { get; set; }
        public string vencod { get; set; }
        public string Estacion { get; set; }
        public string venCed { get; set; }
        public string clinit { get; set; }
        public int nIvaInc { get; set; }
        public string est_pedido { get; set; }
        public string nota { get; set; }
        public string Remision { get; set; }
        public string codCodeudor { get; set; }
        public DateTime fecAuto { get; set; }
        public DateTime fecANU { get; set; }
        public DateTime fecFACTURA { get; set; }
        public string factura_pedido { get; set; }
        public DateTime fecREM { get; set; }
        public string motivo { get; set; }
        public string userNO { get; set; }
        public string userSI { get; set; }
        public string tipodoc { get; set; }
        public string direccion { get; set; }
        public string calificacion { get; set; }
        public string mercancia { get; set; }
        public string BusquedaIdx { get; set; }
        public string user_save { get; set; }
        public DateTime fecha_save { get; set; }
        public DateTime fechaReq { get; set; }
        public int SaldoCupo { get; set; }
        public string bandera { get; set; }
        public string otnumero { get; set; }
        public string ocref { get; set; }
        public string fechaocref { get; set; }
    }
}
