// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_PROYECCIONResult
    {
        public int? Cuota { get; set; }
        public DateTime? FecVenc { get; set; }
        public decimal? VlrCuota { get; set; }
        public decimal? Extra { get; set; }
        public decimal? AbnCapital { get; set; }
        public decimal? Intereses { get; set; }
        public decimal? Saldo { get; set; }
        public string Base { get; set; }
        public decimal? Poliza { get; set; }
        public decimal? SegVida { get; set; }
        public decimal? Otro { get; set; }
    }
}
