// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_SALDO_CLIENTEResult
    {
        public bool? Seleccion { get; set; }
        public string Identificacion { get; set; }
        public string Cliente { get; set; }
        public decimal? Saldo { get; set; }
        public string Codigo { get; set; }
        public string Calificacion { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    }
}
