// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_SaldoInicialMttoResult
    {
        public string nombre_activo { get; set; }
        public string codigo_activo { get; set; }
        public decimal? kilometro { get; set; }
        public decimal? horometro { get; set; }
        public int? movimiento { get; set; }
        public DateTime? fecha { get; set; }
        public string tipo_equipo { get; set; }
        public int SEL { get; set; }
        public string tipo_LecBase { get; set; }
        public int LecBase { get; set; }
        public int id_activo { get; set; }
    }
}
