// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SP_SALDO_CLIENTE_ESTABLECIMIENTOResult
    {
        public int SEL { get; set; }
        public string CLINIT { get; set; }
        public string nombres { get; set; }
        public decimal? SALDO { get; set; }
        public string CODIGO { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string Calificacion { get; set; }
        public string codigoestablecimiento { get; set; }
    }
}
