// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class sp_SalAnterior_ccoResult
    {
        public decimal? nSuma { get; set; }
        public string Ternom { get; set; }
        public string glnum { get; set; }
        public string glcod { get; set; }
        public string TerCod { get; set; }
        public string TerNit { get; set; }
        public string Mascco { get; set; }
        public string cconom { get; set; }
    }
}
