// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SpGetRelBalanceResult
    {
        public string Cuenta { get; set; }
        public string GLNUM { get; set; }
        public string Codigo { get; set; }
    }
}
