// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SpGetBalConceptosResult
    {
        public int Tipo { get; set; }
        public string Concepto { get; set; }
        public int Codigo { get; set; }
        public decimal Valor1 { get; set; }
        public decimal Valor2 { get; set; }
        public string Editar { get; set; }
        public string Sumatoria { get; set; }
    }
}
