// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SpGetInfoBalResult
    {
        public string Codigo { get; set; }
        public string MasCod { get; set; }
        public decimal? Valor { get; set; }
        public decimal? Valor2 { get; set; }
        public string glnum { get; set; }
        public string Sumatoria { get; set; }
    }
}
