// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SpGetBalanceAperturaArticulosResult
    {
        public string NDocumento { get; set; }
        public string NomFuente { get; set; }
        public string Realizado { get; set; }
        public string Fuente { get; set; }
    }
}
