// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SpGetModCierreByIdResult
    {
        public int Id { get; set; }
        public string ModNum { get; set; }
        public string ModDb { get; set; }
        public string ModCr { get; set; }
        public string ModPer { get; set; }
        public string ModFte { get; set; }
        public string ModTer { get; set; }
        public string ModCco { get; set; }
    }
}
