// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SpGetGlCierreTerResult
    {
        public int Id { get; set; }
        public string Mes { get; set; }
        public int MesNum { get; set; }
        public int Anno { get; set; }
        public string Documento { get; set; }
        public string Fuente { get; set; }
        public string FuenteNom { get; set; }
        public int Clase { get; set; }
    }
}
