// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SpGetArtiniifinicialResult
    {
        public bool? Checked { get; set; }
        public int Id { get; set; }
        public string cuenta { get; set; }
        public string metodo { get; set; }
        public string arcod { get; set; }
        public string arespe { get; set; }
        public string marnom { get; set; }
        public string linnom { get; set; }
        public string desnom { get; set; }
        public decimal arcostohist { get; set; }
        public decimal arcant { get; set; }
        public decimal arprovision { get; set; }
        public decimal arvalorneto { get; set; }
        public decimal arprecioventa { get; set; }
        public decimal arcostoterm { get; set; }
        public decimal argastosdirventa { get; set; }
        public decimal arvnr { get; set; }
        public decimal arcr { get; set; }
        public decimal ardeterioro { get; set; }
    }
}
