// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class SpObtenerLogMovNiifResult
    {
        public int Id { get; set; }
        public string Mensaje { get; set; }
        public DateTime InsDateTime { get; set; }
        public string Estado { get; set; }
        public string Cuenta { get; set; }
    }
}
