// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class spOITCompaniesResult
    {
        public string TipoDocumento { get; set; }
        public string Identificacion { get; set; }
        public string DigitoVerificacion { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public int? TipoPersona { get; set; }
        public int? Regimen { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string TipoDocumentoRepLegal { get; set; }
        public string NombreRepLegal { get; set; }
        public string IdentificacionRepLegal { get; set; }
        public string TelefonoRepLegal { get; set; }
        public string EmailRepLegal { get; set; }
        public string Pais { get; set; }
        public string Departamento { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public string CodigoActividad { get; set; }
        public string NombreActividad { get; set; }
        public string RegistroMercantil { get; set; }
    }
}
