// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class usp_proclientesResult
    {
        public string clicod { get; set; }
        public string clicel1 { get; set; }
        public string cliciud { get; set; }
        public string cliCodCiud { get; set; }
        public string clidir { get; set; }
        public string climail { get; set; }
        public string clinit { get; set; }
        public string clinom { get; set; }
        public string cliPais { get; set; }
        public int cliPersona { get; set; }
        public string cliPriApe { get; set; }
        public string cliPriNom { get; set; }
        public string cliSegApe { get; set; }
        public string cliSegNom { get; set; }
        public string clitel { get; set; }
        public string digVer { get; set; }
        public string tipDoc { get; set; }
    }
}
