// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class usp_proaccglproResult
    {
        public string pronit { get; set; }
        public string digVer { get; set; }
        public string procel { get; set; }
        public string prociud { get; set; }
        public string proCodCiud { get; set; }
        public string prodir { get; set; }
        public string promail { get; set; }
        public string PRONIT1 { get; set; }
        public string pronom { get; set; }
        public string proPais { get; set; }
        public int proPersona { get; set; }
        public string proPriApe { get; set; }
        public string proPriNom { get; set; }
        public string proSegApe { get; set; }
        public string proSegNom { get; set; }
        public string protel { get; set; }
        public string tipDocu { get; set; }
    }
}
