// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class usp_FacelGLManageDocumentsResult
    {
        public string PREFIJO { get; set; }
        public string CONSECUTIVO { get; set; }
        public string NITOFE { get; set; }
        public string NITADQ { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public DateTime? FECHA { get; set; }
        public string HORA { get; set; }
        public string VENCIMIENTO { get; set; }
        public string OBSERVACION { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal IMPUESTOS { get; set; }
        public decimal TOTAL { get; set; }
        public decimal CARGOS { get; set; }
        public decimal DESCUENTOS { get; set; }
        public decimal RETENCIONES { get; set; }
        public decimal ANTICIPOS { get; set; }
        public string NroFac { get; set; }
        public int? IdOpen { get; set; }
        public string CUFE { get; set; }
        public string ESTADO { get; set; }
        public string DocPruebas { get; set; }
        public string clicod { get; set; }
        public string Moneda { get; set; }
        public string Rechazo { get; set; }
        public decimal RTEFUENTE { get; set; }
        public decimal RTEICA { get; set; }
        public decimal RTEIVA { get; set; }
        public string TipoDoc { get; set; }
        public string ZipKey { get; set; }
        public string UrlInvoiceXml { get; set; }
        public string UrlInvoicePdf { get; set; }
        public string UrlInvoiceAttached { get; set; }
        public string Emisor { get; set; }
        public string Emails { get; set; }
        public string emailempresa { get; set; }
        public string SENDER { get; set; }
        public string TemplateId { get; set; }
        public string Titular { get; set; }
    }
}
