// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class usp_FacelGLManageCompaniesResult
    {
        public int? TipoDocumento { get; set; }
        public string Identificacion { get; set; }
        public string DigitoVerificacion { get; set; }
        public string RazonSocial { get; set; }
        public int TipoPersona { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int Regimen { get; set; }
        public string Email { get; set; }
        public int? Municipio { get; set; }
        public string RegistroMercantil { get; set; }
        public decimal ResponsabilidadFiscal { get; set; }
    }
}
