// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class usp_protercerosResult
    {
        public string tercod { get; set; }
        public string digVer { get; set; }
        public string tercel { get; set; }
        public string TerCiu { get; set; }
        public string terCodCiu { get; set; }
        public string terdir { get; set; }
        public string termail { get; set; }
        public string ternit { get; set; }
        public string ternom { get; set; }
        public string terPais { get; set; }
        public int terPersona { get; set; }
        public string TerPriApe { get; set; }
        public string TerPriNom { get; set; }
        public string TerSegApe { get; set; }
        public string TerSegNom { get; set; }
        public string tertel { get; set; }
        public string tipDoc { get; set; }
    }
}
