// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace generalapi.Models
{
    public partial class usp_FacelGLManageResolutionsResult
    {
        public int? Id { get; set; }
        public int? CompanyId { get; set; }
        public string TypeDocumentId { get; set; }
        public string Resolution { get; set; }
        public string Prefix { get; set; }
        public string ResolutionDate { get; set; }
        public string TechnicalKey { get; set; }
        public int? RFrom { get; set; }
        public int? RTo { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
        public string Clinom { get; set; }
    }
}
